In [5]:
import requests
import pandas as pd

In [6]:
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=TSLA&apikey=PLWHFCZSI5GFFUMN'
r = requests.get(url)
tesla_weekly_data = r.json()

print(tesla_weekly_data)

{'Meta Data': {'1. Information': 'Weekly Prices (open, high, low, close) and Volumes', '2. Symbol': 'TSLA', '3. Last Refreshed': '2021-10-08', '4. Time Zone': 'US/Eastern'}, 'Weekly Time Series': {'2021-10-08': {'1. open': '796.5000', '2. high': '806.9699', '3. low': '773.2200', '4. close': '785.4900', '5. volume': '99483120'}, '2021-10-01': {'1. open': '773.1200', '2. high': '799.0000', '3. low': '763.5900', '4. close': '775.2200', '5. volume': '109382331'}, '2021-09-24': {'1. open': '734.5577', '2. high': '774.8000', '3. low': '718.6249', '4. close': '774.3900', '5. volume': '89535196'}, '2021-09-17': {'1. open': '740.2143', '2. high': '761.0400', '3. low': '708.8500', '4. close': '759.4900', '5. volume': '98962617'}, '2021-09-10': {'1. open': '740.0000', '2. high': '764.4500', '3. low': '734.5201', '4. close': '736.2700', '5. volume': '68094762'}, '2021-09-03': {'1. open': '714.7150', '2. high': '741.9900', '3. low': '712.7300', '4. close': '733.5700', '5. volume': '80731775'}, '2021-08-27': {'1. open': '685.4420', '2. high': '716.9700', '3. low': '680.7505', '4. close': '711.9200', '5. volume': '73041547'}, '2021-08-20': {'1. open': '705.0700', '2. high': '709.5000', '3. low': '648.8400', '4. close': '680.2600', '5. volume': '96329308'}, '2021-08-13': {'1. open': '710.1700', '2. high': '729.9000', '3. low': '699.4000', '4. close': '717.1700', '5. volume': '72301742'}, '2021-08-06': {'1. open': '700.0000', '2. high': '726.9400', '3. low': '697.6300', '4. close': '699.1000', '5. volume': '100781351'}, '2021-07-30': {'1. open': '650.9700', '2. high': '697.5300', '3. low': '627.2400', '4. close': '687.2000', '5. volume': '133501299'}, '2021-07-23': {'1. open': '629.8900', '2. high': '664.8599', '3. low': '621.2900', '4. close': '643.3800', '5. volume': '80448226'}, '2021-07-16': {'1. open': '662.2000', '2. high': '693.2800', '3. low': '637.8800', '4. close': '644.2200', '5. volume': '105114865'}, '2021-07-09': {'1. open': '681.7115', '2. high': '684.0000', '3. low': '620.4600', '4. close': '656.9500', '5. volume': '82990274'}, '2021-07-02': {'1. open': '671.6400', '2. high': '700.0000', '3. low': '670.3200', '4. close': '678.9000', '5. volume': '103666230'}, '2021-06-25': {'1. open': '624.4800', '2. high': '697.6200', '3. low': '608.8800', '4. close': '671.8700', '5. volume': '153549954'}, '2021-06-18': {'1. open': '612.2300', '2. high': '628.3500', '3. low': '593.5000', '4. close': '623.3100', '5. volume': '107296122'}, '2021-06-11': {'1. open': '591.8250', '2. high': '623.0900', '3. low': '582.8800', '4. close': '609.8900', '5. volume': '105306562'}, '2021-06-04': {'1. open': '627.8000', '2. high': '633.8000', '3. low': '571.2200', '4. close': '599.0500', '5. volume': '95536458'}, '2021-05-28': {'1. open': '581.6000', '2. high': '635.5900', '3. low': '573.6500', '4. close': '625.2200', '5. volume': '140310958'}, '2021-05-21': {'1. open': '575.5531', '2. high': '596.6800', '3. low': '546.9800', '4. close': '580.8800', '5. volume': '165651036'}, '2021-05-14': {'1. open': '664.9000', '2. high': '665.0500', '3. low': '559.6500', '4. close': '589.7400', '5. volume': '189275731'}, '2021-05-07': {'1. open': '703.8000', '2. high': '706.0000', '3. low': '650.0000', '4. close': '672.3700', '5. volume': '129938147'}, '2021-04-30': {'1. open': '741.0000', '2. high': '749.3000', '3. low': '666.1400', '4. close': '709.4400', '5. volume': '152350715'}, '2021-04-23': {'1. open': '719.6000', '2. high': '753.7700', '3. low': '691.8001', '4. close': '729.4000', '5. volume': '170514922'}, '2021-04-16': {'1. open': '685.7000', '2. high': '780.7900', '3. low': '682.0900', '4. close': '739.7800', '5. volume': '178634338'}, '2021-04-09': {'1. open': '707.7100', '2. high': '708.1600', '3. low': '667.8400', '4. close': '677.0200', '5. volume': '141785455'}, '2021-04-01': {'1. open': '615.6400', '2. high': '692.4203', '3. low': '591.0100', '4. close': '661.7500', '5. volume': '136705010'}, '2021-03-26': {'1. open': '684.5900', '2. high': '699.6200', '3. low': '599.8900', '4. close': '618.7100', '5. volume': '176876942'}, '2021-03-19': {'1. open': '694.0900', '2. high': '713.1800', '3. low': '624.6201', '4. close': '654.8700', '5. volume': '178254604'}, '2021-03-12': {'1. open': '600.5500', '2. high': '717.8500', '3. low': '558.7900', '4. close': '693.7300', '5. volume': '249753690'}, '2021-03-05': {'1. open': '690.1100', '2. high': '721.1100', '3. low': '539.4900', '4. close': '597.9500', '5. volume': '235272714'}, '2021-02-26': {'1. open': '762.6400', '2. high': '768.5000', '3. low': '619.0000', '4. close': '675.5000', '5. volume': '217862425'}, '2021-02-19': {'1. open': '818.0000', '2. high': '821.0000', '3. low': '762.0100', '4. close': '781.3000', '5. volume': '82596163'}, '2021-02-12': {'1. open': '869.6700', '2. high': '877.7700', '3. low': '785.3306', '4. close': '816.1200', '5. volume': '116303534'}, '2021-02-05': {'1. open': '814.2900', '2. high': '880.5000', '3. low': '795.5601', '4. close': '852.2300', '5. volume': '102112291'}, '2021-01-29': {'1. open': '855.0000', '2. high': '900.4000', '3. low': '780.1000', '4. close': '793.5300', '5. volume': '153007757'}, '2021-01-22': {'1. open': '837.8000', '2. high': '859.5000', '3. low': '828.6200', '4. close': '846.6400', '5. volume': '91697493'}, '2021-01-15': {'1. open': '849.4000', '2. high': '868.0000', '3. low': '803.6222', '4. close': '826.1600', '5. volume': '208896134'}, '2021-01-08': {'1. open': '719.4600', '2. high': '884.4900', '3. low': '717.1895', '4. close': '880.0200', '5. volume': '252137795'}, '2020-12-31': {'1. open': '674.5100', '2. high': '718.7200', '3. low': '655.0000', '4. close': '705.6700', '5. volume': '146960321'}, '2020-12-24': {'1. open': '666.2400', '2. high': '668.5000', '3. low': '614.2300', '4. close': '661.7700', '5. volume': '165945448'}, '2020-12-18': {'1. open': '619.0000', '2. high': '695.0000', '3. low': '605.0000', '4. close': '695.0000', '5. volume': '417756359'}, '2020-12-11': {'1. open': '604.9197', '2. high': '654.3200', '3. low': '566.3400', '4. close': '609.9900', '5. volume': '305424055'}, '2020-12-04': {'1. open': '602.2100', '2. high': '607.8000', '3. low': '541.2100', '4. close': '599.0400', '5. volume': '221865368'}, '2020-11-27': {'1. open': '503.5000', '2. high': '598.7800', '3. low': '501.7900', '4. close': '585.7600', '5. volume': '188810315'}, '2020-11-20': {'1. open': '408.9300', '2. high': '508.6112', '3. low': '404.0868', '4. close': '489.6100', '5. volume': '261458208'}, '2020-11-13': {'1. open': '439.5000', '2. high': '452.5000', '3. low': '396.0301', '4. close': '408.5000', '5. volume': '122245822'}, '2020-11-06': {'1. open': '394.0000', '2. high': '440.0000', '3. low': '392.3000', '4. close': '429.9500', '5. volume': '145636427'}, '2020-10-30': {'1. open': '411.6300', '2. high': '430.5000', '3. low': '379.1100', '4. close': '388.0400', '5. volume': '141620023'}, '2020-10-23': {'1. open': '446.2400', '2. high': '447.0000', '3. low': '407.3801', '4. close': '420.6300', '5. volume': '174024764'}, '2020-10-16': {'1. open': '442.0000', '2. high': '465.9000', '3. low': '436.6000', '4. close': '439.6700', '5. volume': '189748425'}, '2020-10-09': {'1. open': '423.3500', '2. high': '439.0000', '3. low': '406.0500', '4. close': '434.0000', '5. volume': '206343526'}, '2020-10-02': {'1. open': '424.6200', '2. high': '448.8800', '3. low': '411.6000', '4. close': '415.0900', '5. volume': '270378010'}, '2020-09-25': {'1. open': '453.1300', '2. high': '455.6800', '3. low': '351.3000', '4. close': '407.3400', '5. volume': '447901291'}, '2020-09-18': {'1. open': '380.9500', '2. high': '461.9400', '3. low': '373.3000', '4. close': '442.1500', '5. volume': '416051578'}, '2020-09-11': {'1. open': '356.0000', '2. high': '398.9900', '3. low': '329.8800', '4. close': '372.7200', '5. volume': '340579527'}, '2020-09-04': {'1. open': '444.6100', '2. high': '502.4900', '3. low': '372.0201', '4. close': '418.3200', '5. volume': '500060538'}, '2020-08-28': {'1. open': '2126.2750', '2. high': '2318.4900', '3. low': '1927.5200', '4. close': '2213.4000', '5. volume': '88736115'}, '2020-08-21': {'1. open': '1677.0000', '2. high': '2095.4900', '3. low': '1672.8300', '4. close': '2049.9800', '5. volume': '90804281'}, '2020-08-14': {'1. open': '1448.0000', '2. high': '1668.8000', '3. low': '1365.0000', '4. close': '1650.7100', '5. volume': '71049854'}, '2020-08-07': {'1. open': '1449.2000', '2. high': '1527.4100', '3. low': '1415.0100', '4. close': '1452.7100', '5. volume': '37091084'}, '2020-07-31': {'1. open': '1435.0000', '2. high': '1564.7000', '3. low': '1413.0003', '4. close': '1430.7600', '5. volume': '61152261'}, '2020-07-24': {'1. open': '1519.0100', '2. high': '1689.0000', '3. low': '1366.5401', '4. close': '1417.0000', '5. volume': '91164900'}, '2020-07-17': {'1. open': '1659.0000', '2. high': '1794.9900', '3. low': '1431.0000', '4. close': '1500.8400', '5. volume': '102402100'}, '2020-07-10': {'1. open': '1276.6900', '2. high': '1548.9200', '3. low': '1266.0400', '4. close': '1544.6500', '5. volume': '93426100'}, '2020-07-02': {'1. open': '969.0100', '2. high': '1228.0000', '3. low': '948.5201', '4. close': '1208.6600', '5. volume': '56473104'}, '2020-06-26': {'1. open': '999.9500', '2. high': '1012.0000', '3. low': '937.1500', '4. close': '959.7400', '5. volume': '41796700'}, '2020-06-19': {'1. open': '917.7900', '2. high': '1019.2000', '3. low': '908.5000', '4. close': '1000.9000', '5. volume': '58049300'}, '2020-06-12': {'1. open': '919.0000', '2. high': '1027.4800', '3. low': '909.1600', '4. close': '935.2800', '5. volume': '76773000'}, '2020-06-05': {'1. open': '858.0000', '2. high': '908.6600', '3. low': '854.1000', '4. close': '885.6600', '5. volume': '53154200'}, '2020-05-29': {'1. open': '834.5000', '2. high': '835.0000', '3. low': '785.0000', '4. close': '835.0000', '5. volume': '38707300'}, '2020-05-22': {'1. open': '827.7800', '2. high': '834.7200', '3. low': '796.0000', '4. close': '816.8800', '5. volume': '50886000'}, '2020-05-15': {'1. open': '790.5100', '2. high': '843.2900', '3. low': '763.3000', '4. close': '799.1700', '5. volume': '75692600'}, '2020-05-08': {'1. open': '701.0000', '2. high': '824.0000', '3. low': '698.0000', '4. close': '819.4200', '5. volume': '75009800'}, '2020-05-01': {'1. open': '737.6100', '2. high': '869.8200', '3. low': '683.0400', '4. close': '701.3200', '5. volume': '113123100'}, '2020-04-24': {'1. open': '732.7000', '2. high': '765.5700', '3. low': '673.7900', '4. close': '725.1500', '5. volume': '75654800'}, '2020-04-17': {'1. open': '590.1600', '2. high': '774.9500', '3. low': '580.5300', '4. close': '753.8900', '5. volume': '110415000'}, '2020-04-09': {'1. open': '511.2000', '2. high': '575.1800', '3. low': '497.9600', '4. close': '573.0000', '5. volume': '59127600'}, '2020-04-03': {'1. open': '510.2600', '2. high': '542.9600', '3. low': '446.4000', '4. close': '480.0100', '5. volume': '85543300'}, '2020-03-27': {'1. open': '433.6000', '2. high': '560.0000', '3. low': '410.5000', '4. close': '514.3600', '5. volume': '92330500'}, '2020-03-20': {'1. open': '469.5000', '2. high': '494.8700', '3. low': '350.5100', '4. close': '427.5300', '5. volume': '126751300'}, '2020-03-13': {'1. open': '605.3900', '2. high': '668.0000', '3. low': '502.0000', '4. close': '546.6200', '5. volume': '87540000'}, '2020-03-06': {'1. open': '711.2600', '2. high': '806.9800', '3. low': '684.2700', '4. close': '703.4800', '5. volume': '84543600'}, '2020-02-28': {'1. open': '839.0000', '2. high': '863.5000', '3. low': '611.5200', '4. close': '667.9900', '5. volume': '95409600'}, '2020-02-21': {'1. open': '841.6000', '2. high': '944.7800', '3. low': '832.3600', '4. close': '901.0000', '5. volume': '73754400'}, '2020-02-14': {'1. open': '800.0000', '2. high': '819.9900', '3. low': '735.0000', '4. close': '800.0300', '5. volume': '90392200'}, '2020-02-07': {'1. open': '673.6900', '2. high': '968.9900', '3. low': '673.5200', '4. close': '748.0700', '5. volume': '213540400'}, '2020-01-31': {'1. open': '541.9900', '2. high': '653.0000', '3. low': '539.2800', '4. close': '650.5700', '5. volume': '87923100'}, '2020-01-24': {'1. open': '530.2500', '2. high': '594.5000', '3. low': '528.4100', '4. close': '564.8200', '5. volume': '83177100'}, '2020-01-17': {'1. open': '493.5000', '2. high': '547.4100', '3. low': '492.0000', '4. close': '510.5000', '5. volume': '108248400'}, '2020-01-10': {'1. open': '440.4700', '2. high': '498.8000', '3. low': '440.0000', '4. close': '478.1500', '5. volume': '100559300'}, '2020-01-03': {'1. open': '428.7900', '2. high': '454.0000', '3. low': '402.0800', '4. close': '443.0100', '5. volume': '50182700'}, '2019-12-27': {'1. open': '411.7800', '2. high': '435.3100', '3. low': '410.0000', '4. close': '430.3800', '5. volume': '41953900'}, '2019-12-20': {'1. open': '362.5500', '2. high': '413.0000', '3. low': '362.5000', '4. close': '405.5900', '5. volume': '73651800'}, '2019-12-13': {'1. open': '336.5900', '2. high': '365.2100', '3. low': '335.0800', '4. close': '358.3900', '5. volume': '39084000'}, '2019-12-06': {'1. open': '329.4000', '2. high': '338.8600', '3. low': '327.2500', '4. close': '335.8900', '5. volume': '29518200'}, '2019-11-29': {'1. open': '344.3200', '2. high': '344.5700', '3. low': '327.1000', '4. close': '329.9400', '5. volume': '28308100'}, '2019-11-22': {'1. open': '352.9200', '2. high': '361.2000', '3. low': '330.0000', '4. close': '333.0400', '5. volume': '41830900'}, '2019-11-15': {'1. open': '343.9500', '2. high': '356.3300', '3. low': '342.0000', '4. close': '352.1700', '5. volume': '37040100'}, '2019-11-08': {'1. open': '314.8000', '2. high': '341.5000', '3. low': '309.2600', '4. close': '337.1400', '5. volume': '44207800'}, '2019-11-01': {'1. open': '327.5400', '2. high': '340.8400', '3. low': '309.8000', '4. close': '313.3100', '5. volume': '52647300'}, '2019-10-25': {'1. open': '258.3300', '2. high': '330.0000', '3. low': '250.1800', '4. close': '328.1300', '5. volume': '74609200'}, '2019-10-18': {'1. open': '247.9000', '2. high': '264.7800', '3. low': '247.1300', '4. close': '256.9500', '5. volume': '33841000'}, '2019-10-11': {'1. open': '229.8000', '2. high': '251.0800', '3. low': '228.5500', '4. close': '247.8900', '5. volume': '38395500'}, '2019-10-04': {'1. open': '243.0000', '2. high': '245.9500', '3. low': '224.2800', '4. close': '231.4300', '5. volume': '40753300'}, '2019-09-27': {'1. open': '240.0000', '2. high': '248.7100', '3. low': '218.3600', '4. close': '242.1300', '5. volume': '49659700'}, '2019-09-20': {'1. open': '246.0000', '2. high': '248.1700', '3. low': '238.1600', '4. close': '240.6200', '5. volume': '23912500'}, '2019-09-13': {'1. open': '230.0000', '2. high': '253.5000', '3. low': '228.9400', '4. close': '245.2000', '5. volume': '33623500'}, '2019-09-06': {'1. open': '224.0800', '2. high': '229.8000', '3. low': '219.2100', '4. close': '227.4500', '5. volume': '22699800'}, '2019-08-30': {'1. open': '213.6000', '2. high': '232.4400', '3. low': '211.5400', '4. close': '225.6100', '5. volume': '28193700'}, '2019-08-23': {'1. open': '224.2100', '2. high': '229.0900', '3. low': '211.0000', '4. close': '211.4000', '5. volume': '32326700'}, '2019-08-16': {'1. open': '232.9900', '2. high': '236.0000', '3. low': '211.5500', '4. close': '219.9400', '5. volume': '32441576'}, '2019-08-09': {'1. open': '229.6000', '2. high': '239.8000', '3. low': '225.7500', '4. close': '235.0100', '5. volume': '26541500'}, '2019-08-02': {'1. open': '227.0900', '2. high': '246.6800', '3. low': '226.0300', '4. close': '234.3400', '5. volume': '40956500'}, '2019-07-26': {'1. open': '258.7500', '2. high': '266.0700', '3. low': '222.2500', '4. close': '228.0400', '5. volume': '55384300'}, '2019-07-19': {'1. open': '248.0000', '2. high': '259.9600', '3. low': '244.8600', '4. close': '258.1800', '5. volume': '40726700'}, '2019-07-12': {'1. open': '231.2400', '2. high': '245.3800', '3. low': '227.2800', '4. close': '245.0800', '5. volume': '37931900'}, '2019-07-05': {'1. open': '230.2100', '2. high': '241.5700', '3. low': '222.2200', '4. close': '233.1000', '5. volume': '38763800'}, '2019-06-28': {'1. open': '223.2400', '2. high': '227.2300', '3. low': '217.3500', '4. close': '223.4600', '5. volume': '33631200'}, '2019-06-21': {'1. open': '215.4800', '2. high': '234.7400', '3. low': '214.2700', '4. close': '221.8600', '5. volume': '51626435'}, '2019-06-14': {'1. open': '210.2500', '2. high': '223.3800', '3. low': '207.5100', '4. close': '214.9200', '5. volume': '53037700'}, '2019-06-07': {'1. open': '185.5100', '2. high': '211.0000', '3. low': '176.9900', '4. close': '204.5000', '5. volume': '76614927'}, '2019-05-31': {'1. open': '191.2000', '2. high': '195.0000', '3. low': '184.1000', '4. close': '185.1600', '5. volume': '40601200'}, '2019-05-24': {'1. open': '202.8000', '2. high': '207.4000', '3. low': '186.2200', '4. close': '190.6300', '5. volume': '97899000'}, '2019-05-17': {'1. open': '232.0100', '2. high': '234.5000', '3. low': '208.9200', '4. close': '211.0300', '5. volume': '50653200'}, '2019-05-10': {'1. open': '250.0200', '2. high': '258.3500', '3. low': '236.0200', '4. close': '239.5200', '5. volume': '40861400'}, '2019-05-03': {'1. open': '235.8600', '2. high': '256.6100', '3. low': '231.5000', '4. close': '255.0300', '5. volume': '78749600'}, '2019-04-26': {'1. open': '269.0000', '2. high': '269.6800', '3. low': '231.1300', '4. close': '235.1400', '5. volume': '78006000'}, '2019-04-18': {'1. open': '268.6300', '2. high': '275.0000', '3. low': '258.6300', '4. close': '273.2600', '5. volume': '28310000'}, '2019-04-12': {'1. open': '277.6900', '2. high': '281.1600', '3. low': '265.6000', '4. close': '267.7000', '5. volume': '39957600'}, '2019-04-05': {'1. open': '282.6200', '2. high': '296.1700', '3. low': '260.5900', '4. close': '274.9600', '5. volume': '58278200'}, '2019-03-29': {'1. open': '259.7100', '2. high': '280.3300', '3. low': '254.4600', '4. close': '279.8600', '5. volume': '39110500'}, '2019-03-22': {'1. open': '276.0000', '2. high': '278.0500', '3. low': '263.4600', '4. close': '264.5300', '5. volume': '43669700'}, '2019-03-15': {'1. open': '283.5200', '2. high': '295.3900', '3. low': '274.4000', '4. close': '275.4300', '5. volume': '43600800'}, '2019-03-08': {'1. open': '298.1200', '2. high': '299.0000', '3. low': '270.1000', '4. close': '284.1400', '5. volume': '64459100'}, '2019-03-01': {'1. open': '297.9100', '2. high': '320.0000', '3. low': '288.7700', '4. close': '294.7900', '5. volume': '59787600'}, '2019-02-22': {'1. open': '306.5600', '2. high': '311.5400', '3. low': '290.5000', '4. close': '294.7100', '5. volume': '25903940'}, '2019-02-15': {'1. open': '311.6000', '2. high': '318.6000', '3. low': '301.0000', '4. close': '307.8800', '5. volume': '26888700'}, '2019-02-08': {'1. open': '312.9800', '2. high': '324.2400', '3. low': '298.5000', '4. close': '305.8000', '5. volume': '31498200'}, '2019-02-01': {'1. open': '292.9100', '2. high': '316.1000', '3. low': '287.7500', '4. close': '312.2100', '5. volume': '42147900'}, '2019-01-25': {'1. open': '304.8200', '2. high': '308.0000', '3. low': '279.2800', '4. close': '297.0400', '5. volume': '39858500'}, '2019-01-18': {'1. open': '342.3800', '2. high': '352.0000', '3. low': '299.7300', '4. close': '302.2600', '5. volume': '43823100'}, '2019-01-11': {'1. open': '321.7200', '2. high': '348.4100', '3. low': '317.7500', '4. close': '347.2600', '5. volume': '31088100'}, '2019-01-04': {'1. open': '337.7900', '2. high': '339.2100', '3. low': '297.3800', '4. close': '317.6900', '5. volume': '32320238'}, '2018-12-28': {'1. open': '313.5000', '2. high': '336.2400', '3. low': '294.0900', '4. close': '333.8700', '5. volume': '32231292'}, '2018-12-21': {'1. open': '362.0000', '2. high': '365.7000', '3. low': '311.8700', '4. close': '319.7700', '5. volume': '40109500'}, '2018-12-14': {'1. open': '360.0000', '2. high': '377.8700', '3. low': '353.1200', '4. close': '365.7100', '5. volume': '31646700'}, '2018-12-07': {'1. open': '36

In [7]:
tesla_weekly_df = pd.DataFrame.from_dict(tesla_weekly_data['Weekly Time Series']).T
tesla_weekly_df.head(50)

             1. open   2. high    3. low  4. close  5. volume
2021-10-08  796.5000  806.9699  773.2200  785.4900   99483120
2021-10-01  773.1200  799.0000  763.5900  775.2200  109382331
2021-09-24  734.5577  774.8000  718.6249  774.3900   89535196
2021-09-17  740.2143  761.0400  708.8500  759.4900   98962617
2021-09-10  740.0000  764.4500  734.5201  736.2700   68094762
2021-09-03  714.7150  741.9900  712.7300  733.5700   80731775
2021-08-27  685.4420  716.9700  680.7505  711.9200   73041547
2021-08-20  705.0700  709.5000  648.8400  680.2600   96329308
2021-08-13  710.1700  729.9000  699.4000  717.1700   72301742
2021-08-06  700.0000  726.9400  697.6300  699.1000  100781351
2021-07-30  650.9700  697.5300  627.2400  687.2000  133501299
2021-07-23  629.8900  664.8599  621.2900  643.3800   80448226
2021-07-16  662.2000  693.2800  637.8800  644.2200  105114865
2021-07-09  681.7115  684.0000  620.4600  656.9500   82990274
2021-07-02  671.6400  700.0000  670.3200  678.9000  103666230
2021-06-25  624.4800  697.6200  608.8800  671.8700  153549954
2021-06-18  612.2300  628.3500  593.5000  623.3100  107296122
2021-06-11  591.8250  623.0900  582.8800  609.8900  105306562
2021-06-04  627.8000  633.8000  571.2200  599.0500   95536458
2021-05-28  581.6000  635.5900  573.6500  625.2200  140310958
2021-05-21  575.5531  596.6800  546.9800  580.8800  165651036
2021-05-14  664.9000  665.0500  559.6500  589.7400  189275731
2021-05-07  703.8000  706.0000  650.0000  672.3700  129938147
2021-04-30  741.0000  749.3000  666.1400  709.4400  152350715
2021-04-23  719.6000  753.7700  691.8001  729.4000  170514922
2021-04-16  685.7000  780.7900  682.0900  739.7800  178634338
2021-04-09  707.7100  708.1600  667.8400  677.0200  141785455
2021-04-01  615.6400  692.4203  591.0100  661.7500  136705010
2021-03-26  684.5900  699.6200  599.8900  618.7100  176876942
2021-03-19  694.0900  713.1800  624.6201  654.8700  178254604
2021-03-12  600.5500  717.8500  558.7900  693.7300  249753690
2021-03-05  690.1100  721.1100  539.4900  597.9500  235272714
2021-02-26  762.6400  768.5000  619.0000  675.5000  217862425
2021-02-19  818.0000  821.0000  762.0100  781.3000   82596163
2021-02-12  869.6700  877.7700  785.3306  816.1200  116303534
2021-02-05  814.2900  880.5000  795.5601  852.2300  102112291
2021-01-29  855.0000  900.4000  780.1000  793.5300  153007757
2021-01-22  837.8000  859.5000  828.6200  846.6400   91697493
2021-01-15  849.4000  868.0000  803.6222  826.1600  208896134
2021-01-08  719.4600  884.4900  717.1895  880.0200  252137795
2020-12-31  674.5100  718.7200  655.0000  705.6700  146960321
2020-12-24  666.2400  668.5000  614.2300  661.7700  165945448
2020-12-18  619.0000  695.0000  605.0000  695.0000  417756359
2020-12-11  604.9197  654.3200  566.3400  609.9900  305424055
2020-12-04  602.2100  607.8000  541.2100  599.0400  221865368
2020-11-27  503.5000  598.7800  501.7900  585.7600  188810315
2020-11-20  408.9300  508.6112  404.0868  489.6100  261458208
2020-11-13  439.5000  452.5000  396.0301  408.5000  122245822
2020-11-06  394.0000  440.0000  392.3000  429.9500  145636427
2020-10-30  411.6300  430.5000  379.1100  388.0400  141620023

In [11]:
url = 'https://www.alphavantage.co/query?function=RSI&symbol=TSLA&interval=weekly&time_period=10&series_type=open&apikey=PLWHFCZSI5GFFUMN'
r = requests.get(url)
tesla_rsi_weekly = r.json()

print(tesla_rsi_weekly_df)

{'Meta Data': {'1: Symbol': 'TSLA', '2: Indicator': 'Relative Strength Index (RSI)', '3: Last Refreshed': '2021-10-08', '4: Interval': 'weekly', '5: Time Period': 10, '6: Series Type': 'open', '7: Time Zone': 'US/Eastern Time'}, 'Technical Analysis: RSI': {'2021-10-08': {'RSI': '69.5571'}, '2021-10-01': {'RSI': '66.4242'}, '2021-09-24': {'RSI': '60.3699'}, '2021-09-17': {'RSI': '61.8421'}, '2021-09-10': {'RSI': '61.8103'}, '2021-09-03': {'RSI': '58.1086'}, '2021-08-27': {'RSI': '53.4023'}, '2021-08-20': {'RSI': '57.2861'}, '2021-08-13': {'RSI': '58.2772'}, '2021-08-06': {'RSI': '56.9401'}, '2021-07-30': {'RSI': '49.9860'}, '2021-07-23': {'RSI': '46.6522'}, '2021-07-16': {'RSI': '51.3763'}, '2021-07-09': {'RSI': '54.3685'}, '2021-07-02': {'RSI': '53.0995'}, '2021-06-25': {'RSI': '46.8734'}, '2021-06-18': {'RSI': '45.1718'}, '2021-06-11': {'RSI': '42.4064'}, '2021-06-04': {'RSI': '46.0955'}, '2021-05-28': {'RSI': '40.0697'}, '2021-05-21': {'RSI': '39.2700'}, '2021-05-14': {'RSI': '47.7416'}, '2021-05-07': {'RSI': '52.1499'}, '2021-04-30': {'RSI': '56.6522'}, '2021-04-23': {'RSI': '54.6239'}, '2021-04-16': {'RSI': '51.3807'}, '2021-04-09': {'RSI': '53.6202'}, '2021-04-01': {'RSI': '44.5156'}, '2021-03-26': {'RSI': '51.3035'}, '2021-03-19': {'RSI': '52.2923'}, '2021-03-12': {'RSI': '42.4660'}, '2021-03-05': {'RSI': '51.6294'}, '2021-02-26': {'RSI': '61.2647'}, '2021-02-19': {'RSI': '70.2740'}, '2021-02-12': {'RSI': '80.1781'}, '2021-02-05': {'RSI': '77.0593'}, '2021-01-29': {'RSI': '86.0128'}, '2021-01-22': {'RSI': '85.3663'}, '2021-01-15': {'RSI': '87.8305'}, '2021-01-08': {'RSI': '82.8353'}, '2020-12-31': {'RSI': '80.3203'}, '2020-12-24': {'RSI': '79.8309'}, '2020-12-18': {'RSI': '76.8749'}, '2020-12-11': {'RSI': '75.9285'}, '2020-12-04': {'RSI': '75.7566'}, '2020-11-27': {'RSI': '68.3484'}, '2020-11-20': {'RSI': '57.0252'}, '2020-11-13': {'RSI': '63.6497'}, '2020-11-06': {'RSI': '56.9507'}, '2020-10-30': {'RSI': '60.8621'}, '2020-10-23': {'RSI': '69.2675'}, '2020-10-16': {'RSI': '68.7923'}, '2020-10-09': {'RSI': '66.7574'}, '2020-10-02': {'RSI': '67.0253'}, '2020-09-25': {'RSI': '72.9377'}, '2020-09-18': {'RSI': '66.1299'}, '2020-09-11': {'RSI': '63.2542'}, '2020-09-04': {'RSI': '86.8138'}, '2020-08-28': {'RSI': '85.7721'}, '2020-08-21': {'RSI': '78.7611'}, '2020-08-14': {'RSI': '72.5578'}, '2020-08-07': {'RSI': '72.6579'}, '2020-07-31': {'RSI': '72.2503'}, '2020-07-24': {'RSI': '78.4804'}, '2020-07-17': {'RSI': '90.1370'}, '2020-07-10': {'RSI': '84.4661'}, '2020-07-02': {'RSI': '73.3801'}, '2020-06-26': {'RSI': '78.4469'}, '2020-06-19': {'RSI': '74.1873'}, '2020-06-12': {'RSI': '74.3821'}, '2020-06-05': {'RSI': '70.9163'}, '2020-05-29': {'RSI': '69.4849'}, '2020-05-22': {'RSI': '69.0935'}, '2020-05-15': {'RSI': '66.9790'}, '2020-05-08': {'RSI': '61.2483'}, '2020-05-01': {'RSI': '65.4280'}, '2020-04-24': {'RSI': '65.1409'}, '2020-04-17': {'RSI': '55.4798'}, '2020-04-09': {'RSI': '48.3421'}, '2020-04-03': {'RSI': '48.2532'}, '2020-03-27': {'RSI': '40.7730'}, '2020-03-20': {'RSI': '43.4183'}, '2020-03-13': {'RSI': '55.7375'}, '2020-03-06': {'RSI': '69.5803'}, '2020-02-28': {'RSI': '95.2756'}, '2020-02-21': {'RSI': '95.9245'}, '2020-02-14': {'RSI': '95.4814'}, '2020-02-07': {'RSI': '93.5709'}, '2020-01-31': {'RSI': '89.3426'}, '2020-01-24': {'RSI': '88.7489'}, '2020-01-17': {'RSI': '86.6545'}, '2020-01-10': {'RSI': '82.3996'}, '2020-01-03': {'RSI': '81.2122'}, '2019-12-27': {'RSI': '79.3898'}, '2019-12-20': {'RSI': '72.4216'}, '2019-12-13': {'RSI': '67.1508'}, '2019-12-06': {'RSI': '65.5076'}, '2019-11-29': {'RSI': '72.2582'}, '2019-11-22': {'RSI': '76.3393'}, '2019-11-15': {'RSI': '75.0146'}, '2019-11-08': {'RSI': '70.1223'}, '2019-11-01': {'RSI': '75.9738'}, '2019-10-25': {'RSI': '59.4156'}, '2019-10-18': {'RSI': '55.2309'}, '2019-10-11': {'RSI': '46.6373'}, '2019-10-04': {'RSI': '53.3602'}, '2019-09-27': {'RSI': '51.9432'}, '2019-09-20': {'RSI': '54.9481'}, '2019-09-13': {'RSI': '47.6846'}, '2019-09-06': {'RSI': '44.7165'}, '2019-08-30': {'RSI': '39.2228'}, '2019-08-23': {'RSI': '43.1278'}, '2019-08-16': {'RSI': '46.5818'}, '2019-08-09': {'RSI': '45.0526'}, '2019-08-02': {'RSI': '43.9841'}, '2019-07-26': {'RSI': '56.4454'}, '2019-07-19': {'RSI': '52.3171'}, '2019-07-12': {'RSI': '45.0025'}, '2019-07-05': {'RSI': '44.5319'}, '2019-06-28': {'RSI': '41.4822'}, '2019-06-21': {'RSI': '38.0704'}, '2019-06-14': {'RSI': '35.7999'}, '2019-06-07': {'RSI': '23.9260'}, '2019-05-31': {'RSI': '24.8784'}, '2019-05-24': {'RSI': '26.8387'}, '2019-05-17': {'RSI': '32.6732'}, '2019-05-10': {'RSI': '37.1553'}, '2019-05-03': {'RSI': '30.3991'}, '2019-04-26': {'RSI': '39.2980'}, '2019-04-18': {'RSI': '39.1189'}, '2019-04-12': {'RSI': '41.8390'}, '2019-04-05': {'RSI': '43.3140'}, '2019-03-29': {'RSI': '33.5104'}, '2019-03-22': {'RSI': '37.6807'}, '2019-03-15': {'RSI': '39.7352'}, '2019-03-08': {'RSI': '43.9195'}, '2019-03-01': {'RSI': '43.8429'}, '2019-02-22': {'RSI': '46.1798'}, '2019-02-15': {'RSI': '47.5077'}, '2019-02-08': {'RSI': '47.8468'}, '2019-02-01': {'RSI': '42.4731'}, '2019-01-25': {'RSI': '44.9465'}, '2019-01-18': {'RSI': '53.8465'}, '2019-01-11': {'RSI': '48.8306'}, '2019-01-04': {'RSI': '52.8516'}, '2018-12-28': {'RSI': '46.9037'}, '2018-12-21': {'RSI': '60.6539'}, '2018-12-14': {'RSI': '60.2211'}, '2018-12-07': {'RSI': '60.2211'}, '2018-11-30': {'RSI': '52.8730'}, '2018-11-23': {'RSI': '62.1207'}, '2018-11-16': {'RSI': '60.5411'}, '2018-11-09': {'RSI': '59.0225'}, '2018-11-02': {'RSI': '58.4686'}, '2018-10-26': {'RSI': '39.9589'}, '2018-10-19': {'RSI': '39.4465'}, '2018-10-12': {'RSI': '40.4948'}, '2018-10-05': {'RSI': '49.4259'}, '2018-09-28': {'RSI': '47.5873'}, '2018-09-21': {'RSI': '45.5237'}, '2018-09-14': {'RSI': '41.3949'}, '2018-09-07': {'RSI': '45.8040'}, '2018-08-31': {'RSI': '50.0730'}, '2018-08-24': {'RSI': '44.2311'}, '2018-08-17': {'RSI': '61.2621'}, '2018-08-10': {'RSI': '57.9752'}, '2018-08-03': {'RSI': '44.5936'}, '2018-07-27': {'RSI': '46.1798'}, '2018-07-20': {'RSI': '48.7742'}, '2018-07-13': {'RSI': '48.8443'}, '2018-07-06': {'RSI': '62.7817'}, '2018-06-29': {'RSI': '55.6940'}, '2018-06-22': {'RSI': '65.1139'}, '2018-06-15': {'RSI': '56.4986'}, '2018-06-08': {'RSI': '46.2704'}, '2018-06-01': {'RSI': '39.0189'}, '2018-05-25': {'RSI': '39.8819'}, '2018-05-18': {'RSI': '47.2097'}, '2018-05-11': {'RSI': '44.7935'}, '2018-05-04': {'RSI': '43.2306'}, '2018-04-27': {'RSI': '42.3545'}, '2018-04-20': {'RSI': '44.4039'}, '2018-04-13': {'RSI': '44.7502'}, '2018-04-06': {'RSI': '28.6197'}, '2018-03-29': {'RSI': '41.1369'}, '2018-03-23': {'RSI': '44.2611'}, '2018-03-16': {'RSI': '48.6582'}, '2018-03-09': {'RSI': '50.0552'}, '2018-03-02': {'RSI': '58.4962'}, '2018-02-23': {'RSI': '51.9178'}, '2018-02-16': {'RSI': '44.2538'}, '2018-02-09': {'RSI': '53.3712'}, '2018-02-02': {'RSI': '54.2369'}, '2018-01-26': {'RSI': '58.5811'}, '2018-01-19': {'RSI': '54.5086'}, '2018-01-12': {'RSI': '45.7972'}, '2018-01-05': {'RSI': '44.0051'}, '2017-12-29': {'RSI': '48.2515'}, '2017-12-22': {'RSI': '57.0808'}, '2017-12-15': {'RSI': '43.7792'}, '2017-12-08': {'RSI': '39.2262'}, '2017-12-01': {'RSI': '41.7528'}, '2017-11-24': {'RSI': '41.9474'}, '2017-11-17': {'RSI': '35.0588'}, '2017-11-10': {'RSI': '37.0487'}, '2017-11-03': {'RSI': '40.7382'}, '2017-10-27': {'RSI': '52.6268'}, '2017-10-20': {'RSI': '54.4337'}, '2017-10-13': {'RSI': '52.8918'}, '2017-10-06': {'RSI': '50.2639'}, '2017-09-29': {'RSI': '54.3305'}, '2017-09-22': {'RSI': '66.7149'}, '2017-09-15': {'RSI': '57.3936'}, '2017-09-08': {'RSI': '58.6467'}, '2017-09-01': {'RSI': '56.3649'}, '2017-08-25': {'RSI': '55.8742'}, '2017-08-18': {'RSI': '64.2522'}, '2017-08-11': {'RSI': '62.2822'}, '2017-08-04': {'RSI': '55.6857'}, '2017-07-28': {'RSI': '53.9404'}, '2017-07-21': {'RSI': '52.4339'}, '2017-07-14': {'RSI': '48.3445'}, '2017-07-07': {'RSI': '74.4917'}, '2017-06-30': {'RSI': '86.5826'}, '2017-06-23': {'RSI': '85.0284'}, '2017-06-16': {'RSI': '82.3511'}, '2017-06-09': {'RSI': '78.3607'}, '2017-06-02': {'RSI': '75.1127'}, '2017-05-26': {'RSI': '70.9717'}, '2017-05-19': {'RSI': '75.7681'}, '2017-05-12': {'RSI': '73.6170'}, '2017-05-05': {'RSI': '76.8855'}, '2017-04-28': {'RSI': '75.4929'}, '2017-04-21': {'RSI': '73.8601'}, '2017-04-13': {'RSI': '78.5176'}, '2017-04-07': {'RSI': '73.2881'}, '2017-03-31': {'RSI': '63.9528'}, '2017-03-24': {'RSI': '63.9528'}, '2017-03-17': {'RSI': '56.5777'}, '2017-03-10': {'RSI': '58.6940'}, '2017-03-03': {'RSI': '58.8608'}, '2017-02-24': {'RSI': '80.4386'}, '2017-02-17': {'RSI': '79.2570'}, '2017-02-10': {'RSI': '73.1362'}, '2017-02-03': {'RSI': '74.6732'}, '2017-01-27': {'RSI': '72.3934'}, '2017-01-20': {'RSI': '68.9476'}, '2017-01-13': {'RSI': '65.6915'}, '2017-01-06': {'RSI': '58.5516'}, '2016-12-30': {'RSI': '58.5672'}, '2016-12-23': {'RSI': '51.3666'}, '2016-12-16': {'RSI': '44.5883'}, '2016-12-09': {'RSI': '36.0729'}, '2016-12-02': {'RSI': '43.6892'}, '2016-11-25': {'RSI': '33.5208'}, '2016-11-18': {'RSI': '35.1400'}, '2016-11-11': {'RSI': '38.2830'}, '2016-11-04': {'RSI': '43.9109'}, '2016-10-28': {'RSI': '42.6404'}, '2016-10-21': {'RSI': '39.3633'}, '2016-10-14': {'RSI': '41.6973'}, '2016-10-07': {'RSI': '48.2549'}, '2016-09-30': {'RSI': '44.0611'}, '2016-09-23': {'RSI': '44.3399'}, '2016-09-16': {'RSI': '35.5276'}, '2016-09-09': {'RSI': '37.3085'}, '2016-09-02': {'RSI': '48.9056'}, '2016-08-26': {'RSI': '51.6550'}, '2016-08-19': {'RSI': '52.8864'}, '2016-08-12': {'RSI': '54.1293'}, '2016-08-05': {'RSI': '58.8440'}, '2016-07-29': {'RSI': '52.2397'}, '2016-07-22': {'RSI': '50.8279'}, '2016-07-15': {'RSI': '50.9930'}, '2016-07-08': {'RSI': '45.9423'}, '2016-07-01': {'RSI': '34.7842'}, '2016-06-24': {'RSI': '48.4427'}, '2016-06-17': {'RSI': '48.4427'}, '2016-06-10': {'RSI': '47.5693'}, '2016-06-03': {'RSI': '50.1377'}, '2016-05-27': {'RSI': '48.5657'}, '2016-05-20': {'RSI': '42.5375'}, '2016-05-13': {'RSI': '45.6475'}, '2016-05-06': {'RSI': '58.8307'}, '2016-04-29': {'RSI': '66.5542'}, '2016-04-22': {'RSI': '66.2842'}, '2016-04-15': {'RSI': '65.8935'}, '2016-04-08': {'RSI': '65.3410'}, '2016-04-01': {'RSI': '59.8953'}, '2016-03-24': {'RSI': '61.7556'}, '2016-03-18': {'RSI': '53.9199'}, '2016-03-11': {'RSI': '47.5375'}, '2016-03-04': {'RSI': '45.1248'}, '2016-02-26': {'RSI': '33.5125'}, '2016-02-19': {'RSI': '26.3199'}, '2016-02-12': {'RSI': '25.3042'}, '2016-02-05': {'RSI': '33.5704'}, '2016-01-29': {'RSI': '37.5069'}, '2016-01-22': {'RSI': '40.8032'}, '2016-01-15': {'RSI': '42.8814'}, '2016-01-08': {'RSI': '50.1257'}, '2015-12-31': {'RSI': '50.4793'}, '2015-12-24': {'RSI': '50.5627'}, '2015-12-18': {'RSI': '44.7369'}, '2015-12-11': {'RSI': '48.4278'}, '2015-12-04': {'RSI': '49.9155'}, '2015-11-27': {'RSI': '44.4980'}, '2015-11-20': {'RSI': '39.9386'}, '2015-11-13': {'RSI': '48.5060'}, '2015-11-06': {'RSI': '37.7526'}, '2015-10-30': {'RSI': '38.4920'}, '2015-10-23': {'RSI': '43.1687'}, '2015-10-16': {'RSI': '41.6885'}, '2015-10-09': {'RSI': '50.3871'}, '2015-10-02': {'RSI': '53.7074'}, '2015-09-25': {'RSI': '56.3092'}, '2015-09-18': {'RSI': '52.2662'}, '2015-09-11': {'RSI': '50.3229'}, '2015-09-04': {'RSI': '50.5433'}, '2015-08-28': {'RSI': '35.3254'}, '2015-08-21': {'RSI': '53.5241'}, '2015-08-14': {'RSI': '45.1307'}, '2015-08-07': {'RSI': '61.2116'}, '2015-07-31': {'RSI': '59.4269'}, '2015-07-24': {'RSI': '68.6902'}, '2015-07-17': {'RSI': '63.4957'}, '2015-07-10': {'RSI': '78.8526'}, '2015-07-02': {'RSI': '72.8322'}, '2015-06-26': {'RSI': '73.0533'}, '2015-06-19': {'RSI': '67.5306'}, '2015-06-12': {'RSI': '68.7012'}, '2015-06-05': {'RSI': '69.2271'}, '2015-05-29': {'RSI': '67.7471'}, '2015-05-22': {'RSI': '67.4905'}, '2015-05-15': {'RSI': '63.3595'}, '2015-05-08': {'RSI': '59.8856'}, '2015-05-01': {'RSI': '57.3645'}, '2015-04-24': {'RSI': '49.3148'}, '2015-04-17': {'RSI': '51.3352'}, '2015-04-10': {'RSI': '44.3544'}, '2015-04-02': {'RSI': '36.3219'}, '2015-03-27': {'RSI': '42.0034'}, '2015-03-20': {'RSI': '37.4810'}, '2015-03-13': {'RSI': '38.4738'}, '2015-03-06': {'RSI': '41.9510'}, '2015-02-27': {'RSI': '48.0461'}, '2015-02-20': {'RSI': '42.2419'}, '2015-02-13': {'RSI': '46.8169'}, '2015-02-06': {'RSI': '39.9132'}, '2015-01-30': {'RSI': '38.5671'}, '2015-01-23': {'RSI': '33.5863'}, '2015-01-16': {'RSI': '36.6724'}, '2015-01-09': {'RSI': '40.9106'}, '2015-01-02': {'RSI': '46.0549'}, '2014-12-26': {'RSI': '42.4138'}, '2014-12-19': {'RSI': '36.4187'}, '2014-12-12': {'RSI': '40.7901'}, '2014-12-05': {'RSI': '49.3242'}, '2014-11-28': {'RSI': '51.3138'}, '2014-11-21': {'RSI': '57.6843'}, '2014-11-14': {'RSI': '49.1948'}, '2014-11-07': {'RSI': '51.1494'}, '2014-10-31': {'RSI': '46.8763'}, '2014-10-24': {'RSI': '43.0158'}, '2014-10-17': {'RSI': '47.9513'}, '2014-10-10': {'RSI': '58.4176'}, '2014-10-03': {'RSI': '51.3905'}, '2014-09-26': {'RSI': '57.7796'}, '2014-09-19': {'RSI': '71.9573'}, '2014-09-12': {'RSI': '74.7262'}, '2014-09-05': {'RSI': '74.1420'}, '2014-08-29': {'RSI': '68.8517'}, '2014-08-22': {'RSI': '72.7685'}, '2014-08-15': {'RSI': '70.4449'}, '2014-08-08': {'RSI': '62.6575'}, '2014-08-01': {'RSI': '57.8598'}, '2014-07-25': {'RSI': '54.2004'}, '2014-07-18': {'RSI': '55.9108'}, '2014-07-11': {'RSI': '60.6307'}, '2014-07-03': {'RSI': '69.0482'}, '2014-06-27': {'RSI': '65.4514'}, '2014-06-20': {'RSI': '54.7214'}, '2014-06-13': {'RSI': '55.5333'}, '2014-06-06': {'RSI': '55.2218'}, '2014-05-30': {'RSI': '55.8983'}, '2014-05-23': {'RSI': '47.1880'}, '2014-05-16': {'RSI': '43.3102'}, '2014-05-09': {'RSI': '57.5223'}, '2014-05-02': {'RSI': '52.3085'}, '2014-04-25': {'RSI': '50.6286'}, '2014-04-17': {'RSI': '57.1567'}, '2014-04-11': {'RSI': '56.2937'}, '2014-04-04': {'RSI': '63.1285'}, '2014-03-28': {'RSI': '73.0180'}, '2014-03-21': {'RSI': '77.2949'}, '2014-03-14': {'RSI': '83.8855'}, '2014-03-07': {'RSI': '82.9681'}, '2014-02-28': {'RSI': '76.7182'}, '2014-02-21': {'RSI': '75.7294'}, '2014-02-14': {'RSI': '70.6555'}, '2014-02-07': {'RSI': '68.2313'}, '2014-01-31': {'RSI': '65.1238'}, '2014-01-24': {'RSI': '63.4940'}, '2014-01-17': {'RSI': '49.7742'}, '2014-01-10': {'RSI': '52.7304'}, '2014-01-03': {'RSI': '53.4893'}, '2013-12-27': {'RSI': '49.8532'}, '2013-12-20': {'RSI': '51.9702'}, '2013-12-13': {'RSI': '45.3671'}, '2013-12-06': {'RSI': '38.2829'}, '2013-11-29': {'RSI': '37.0058'}, '2013-11-22': {'RSI': '41.5056'}, '2013-11-15': {'RSI': '44.0716'}, '2013-11-08': {'RSI': '57.4636'}, '2013-11-01': {'RSI': '61.0683'}, '2013-10-25': {'RSI': '71.2396'}, '2013-10-18': {'RSI': '68.2294'}, '2013-10-11': {'RSI': '74.5569'}, '2013-10-04': {'RSI': '80.4430'}, '2013-09-27': {'RSI': '79.4331'}, '2013-09-20': {'RSI': '75.2366'}, '2013-09-13': {'RSI': '73.8126'}, '2013-09-06': {'RSI': '82.8445'}, '2013-08-30': {'RSI': '81.1813'}, '2013-08-23': {'RSI': '75.5682'}, '2013-08-16': {'RSI': '81.6234'}, '2013-08-09': {'RSI': '79.2784'}, '2013-08-02': {'RSI': '76.1732'}, '2013-07-26': {'RSI': '72.9556'}, '2013-07-19': {'RSI': '87.8298'}, '2013-07-12': {'RSI': '85.4627'}, '2013-07-05': {'RSI': '82.2652'}, '2013-06-28': {'RSI': '77.4947'}, '2013-06-21': {'RSI': '89.4504'}, '2013-06-14': {'RSI': '88.3901'}, '2013-06-07': {'RSI': '88.0879'}, '2013-05-31': {'RSI': '94.7481'}, '2013-05-24': {'RSI': '93.5906'}, '2013-05-17': {'RSI': '92.0611'}, '2013-05-10': {'RSI': '83.4076'}, '2013-05-03': {'RSI': '79.6502'}, '2013-04-26': {'RSI': '76.3621'}, '2013-04-19': {'RSI': '69.1132'}, '2013-04-12': {'RSI': '66.3250'}, '2013-04-05': {'RSI': '67.7276'}, '2013-03-28': {'RSI': '56.5821'}, '2013-03-22': {'RSI': '51.4143'}, '2013-03-15': {'RSI': '65.2846'}, '2013-03-08': {'RSI': '51.8615'}, '2013-03-01': {'RSI': '58.7419'}, '2013-02-22': {'RSI': '65.6110'}, '2013-02-15': {'RSI': '69.3508'}, '2013-02-08': {'RSI': '71.8476'}, '2013-02-01': {'RSI': '68.0519'}, '2013-01-25': {'RSI': '60.9804'}, '2013-01-18': {'RSI': '55.2432'}, '2013-01-11': {'RSI': '65.2831'}, '2013-01-04': {'RSI': '58.1132'}, '2012-12-28': {'RSI': '62.2255'}, '2012-12-21': {'RSI': '63.0411'}, '2012-12-14': {'RSI': '67.0568'}, '2012-12-07': {'RSI': '65.4355'}, '2012-11-30': {'RSI': '59.4873'}, '2012-11-23': {'RSI': '59.3818'}, '2012-11-16': {'RSI': '52.8257'}, '2012-11-09': {'RSI': '50.8607'}, '2012-11-02': {'RSI': '41.4542'}, '2012-10-26': {'RSI': '42.4645'}, '2012-10-19': {'RSI': '42.4966'}, '2012-10-12': {'RSI': '45.1413'}, '2012-10-05': {'RSI': '47.1046'}, '2012-09-28': {'RSI': '47.1335'}, '2012-09-21': {'RSI': '55.8736'}, '2012-09-14': {'RSI': '45.8500'}, '2012-09-07': {'RSI': '43.3499'}, '2012-08-31': {'RSI': '46.3221'}, '2012-08-24': {'RSI': '47.9567'}, '2012-08-17': {'RSI': '46.6120'}, '2012-08-10': {'RSI': '40.1352'}, '2012-08-03': {'RSI': '44.5947'}, '2012-07-27': {'RSI': '48.3973'}, '2012-07-20': {'RSI': '57.8193'}, '2012-07-13': {'RSI': '48.4906'}, '2012-07-06': {'RSI': '49.6903'}, '2012-06-29': {'RSI': '57.8242'}, '2012-06-22': {'RSI': '45.4018'}, '2012-06-15': {'RSI': '46.5430'}, '2012-06-08': {'RSI': '37.8835'}, '2012-06-01': {'RSI': '43.3752'}, '2012-05-25': {'RSI': '32.5802'}, '2012-05-18': {'RSI': '46.9751'}, '2012-05-11': {'RSI': '47.1479'}, '2012-05-04': {'RSI': '52.8814'}, '2012-04-27': {'RSI': '51.2102'}, '2012-04-20': {'RSI': '53.5012'}, '2012-04-13': {'RSI': '56.3476'}, '2012-04-05': {'RSI': '72.6258'}, '2012-03-30': {'RSI': '68.1672'}, '2012-03-23': {'RSI': '67.2569'}, '2012-03-16': {'RSI': '65.7337'}, '2012-03-09': {'RSI': '64.8559'}, '2012-03-02': {'RSI': '62.4635'}, '2012-02-24': {'RSI': '69.0326'}, '2012-02-17': {'RSI': '60.5395'}, '2012-02-10': {'RSI': '59.1736'}, '2012-02-03': {'RSI': '54.0523'}, '2012-01-27': {'RSI': '43.4193'}, '2012-01-20': {'RSI': '42.5713'}, '2012-01-13': {'RSI': '43.7516'}, '2012-01-06': {'RSI': '50.1386'}, '2011-12-30': {'RSI': '45.4060'}, '2011-12-23': {'RSI': '46.7475'}, '2011-12-16': {'RSI': '54.6958'}, '2011-12-09': {'RSI': '68.4734'}, '2011-12-02': {'RSI': '64.4870'}, '2011-11-25': {'RSI': '66.6689'}, '2011-11-18': {'RSI': '69.3569'}, '2011-11-11': {'RSI': '66.3955'}, '2011-11-04': {'RSI': '61.0671'}, '2011-10-28': {'RSI': '56.3191'}, '2011-10-21': {'RSI': '56.2897'}, '2011-10-14': {'RSI': '54.7815'}, '2011-10-07': {'RSI': '47.8299'}, '2011-09-30': {'RSI': '52.6787'}, '2011-09-23': {'RSI': '47.9277'}, '2011-09-16': {'RSI': '40.3195'}, '2011-09-09': {'RSI': '39.4751'}, '2011-09-02': {'RSI': '43.5323'}, '2011-08-26': {'RSI': '39.9474'}, '2011-08-19': {'RSI': '48.7565'}, '2011-08-12': {'RSI': '36.0231'}, '2011-08-05': {'RSI': '55.7533'}, '2011-07-29': {'RSI': '57.4829'}, '2011-07-22': {'RSI': '50.7254'}, '2011-07-15': {'RSI': '55.7909'}, '2011-07-08': {'RSI': '58.8864'}, '2011-07-01': {'RSI': '54.1195'}, '2011-06-24': {'RSI': '48.0704'}, '2011-06-17': {'RSI': '56.3331'}, '2011-06-10': {'RSI': '61.8717'}, '2011-06-03': {'RSI': '65.1752'}, '2011-05-27': {'RSI': '58.1133'}, '2011-05-20': {'RSI': '60.0730'}, '2011-05-13': {'RSI': '56.5442'}, '2011-05-06': {'RSI': '59.4082'}, '2011-04-29': {'RSI': '56.4289'}, '2011-04-21': {'RSI': '50.7541'}, '2011-04-15': {'RSI': '56.3963'}, '2011-04-08': {'RSI': '57.9540'}, '2011-04-01': {'RSI': '41.1787'}, '2011-03-25': {'RSI': '42.4711'}, '2011-03-18': {'RSI': '45.2853'}, '2011-03-11': {'RSI': '49.5445'}, '2011-03-04': {'RSI': '44.5088'}, '2011-02-25': {'RSI': '40.6565'}, '2011-02-18': {'RSI': '43.0325'}, '2011-02-11': {'RSI': '41.4939'}, '2011-02-04': {'RSI': '43.7024'}, '2011-01-28': {'RSI': '41.8695'}, '2011-01-21': {'RSI': '47.0380'}, '2011-01-14': {'RSI': '55.5519'}, '2011-01-07': {'RSI': '51.6584'}, '2010-12-31': {'RSI': '55.5435'}, '2010-12-23': {'RSI': '70.0993'}, '2010-12-17': {'RSI': '70.0993'}, '2010-12-10': {'RSI': '69.5820'}, '2010-12-03': {'RSI': '88.9896'}, '2010-11-26': {'RSI': '85.5615'}, '2010-11-19': {'RSI': '83.9846'}, '2010-11-12': {'RSI': '72.5549'}, '2010-11-05': {'RSI': '61.4823'}, '2010-10-29': {'RSI': '55.1162'}, '2010-10-22': {'RSI': '52.1253'}, '2010-10-15': {'RSI': '51.5720'}, '2010-10-08': {'RSI': '51.5090'}, '2010-10-01': {'RSI': '51.3380'}, '2010-09-24': {'RSI': '52.8478'}, '2010-09-17': {'RSI': '54.0126'}}}

In [12]:
tesla_rsi_weekly_df = pd.DataFrame.from_dict(tesla_rsi_weekly['Technical Analysis: RSI']).T
tesla_rsi_weekly_df.head(50)

                RSI
2021-10-08  69.5571
2021-10-01  66.4242
2021-09-24  60.3699
2021-09-17  61.8421
2021-09-10  61.8103
2021-09-03  58.1086
2021-08-27  53.4023
2021-08-20  57.2861
2021-08-13  58.2772
2021-08-06  56.9401
2021-07-30  49.9860
2021-07-23  46.6522
2021-07-16  51.3763
2021-07-09  54.3685
2021-07-02  53.0995
2021-06-25  46.8734
2021-06-18  45.1718
2021-06-11  42.4064
2021-06-04  46.0955
2021-05-28  40.0697
2021-05-21  39.2700
2021-05-14  47.7416
2021-05-07  52.1499
2021-04-30  56.6522
2021-04-23  54.6239
2021-04-16  51.3807
2021-04-09  53.6202
2021-04-01  44.5156
2021-03-26  51.3035
2021-03-19  52.2923
2021-03-12  42.4660
2021-03-05  51.6294
2021-02-26  61.2647
2021-02-19  70.2740
2021-02-12  80.1781
2021-02-05  77.0593
2021-01-29  86.0128
2021-01-22  85.3663
2021-01-15  87.8305
2021-01-08  82.8353
2020-12-31  80.3203
2020-12-24  79.8309
2020-12-18  76.8749
2020-12-11  75.9285
2020-12-04  75.7566
2020-11-27  68.3484
2020-11-20  57.0252
2020-11-13  63.6497
2020-11-06  56.9507
2020-10-30  60.8621

In [13]:
tesla_weekly_df = tesla_weekly_df.reset_index()

In [14]:
tesla_rsi_weekly_df = tesla_rsi_weekly_df.reset_index()

In [15]:
merged_weekly_rsi = pd.merge(tesla_weekly_df, tesla_rsi_weekly_df , on=['index', 'index'])
merged_weekly_rsi.head(50)

         index   1. open   2. high    3. low  4. close  5. volume      RSI
0   2021-10-08  796.5000  806.9699  773.2200  785.4900   99483120  69.5571
1   2021-10-01  773.1200  799.0000  763.5900  775.2200  109382331  66.4242
2   2021-09-24  734.5577  774.8000  718.6249  774.3900   89535196  60.3699
3   2021-09-17  740.2143  761.0400  708.8500  759.4900   98962617  61.8421
4   2021-09-10  740.0000  764.4500  734.5201  736.2700   68094762  61.8103
5   2021-09-03  714.7150  741.9900  712.7300  733.5700   80731775  58.1086
6   2021-08-27  685.4420  716.9700  680.7505  711.9200   73041547  53.4023
7   2021-08-20  705.0700  709.5000  648.8400  680.2600   96329308  57.2861
8   2021-08-13  710.1700  729.9000  699.4000  717.1700   72301742  58.2772
9   2021-08-06  700.0000  726.9400  697.6300  699.1000  100781351  56.9401
10  2021-07-30  650.9700  697.5300  627.2400  687.2000  133501299  49.9860
11  2021-07-23  629.8900  664.8599  621.2900  643.3800   80448226  46.6522
12  2021-07-16  662.2000  693.2800  637.8800  644.2200  105114865  51.3763
13  2021-07-09  681.7115  684.0000  620.4600  656.9500   82990274  54.3685
14  2021-07-02  671.6400  700.0000  670.3200  678.9000  103666230  53.0995
15  2021-06-25  624.4800  697.6200  608.8800  671.8700  153549954  46.8734
16  2021-06-18  612.2300  628.3500  593.5000  623.3100  107296122  45.1718
17  2021-06-11  591.8250  623.0900  582.8800  609.8900  105306562  42.4064
18  2021-06-04  627.8000  633.8000  571.2200  599.0500   95536458  46.0955
19  2021-05-28  581.6000  635.5900  573.6500  625.2200  140310958  40.0697
20  2021-05-21  575.5531  596.6800  546.9800  580.8800  165651036  39.2700
21  2021-05-14  664.9000  665.0500  559.6500  589.7400  189275731  47.7416
22  2021-05-07  703.8000  706.0000  650.0000  672.3700  129938147  52.1499
23  2021-04-30  741.0000  749.3000  666.1400  709.4400  152350715  56.6522
24  2021-04-23  719.6000  753.7700  691.8001  729.4000  170514922  54.6239
25  2021-04-16  685.7000  780.7900  682.0900  739.7800  178634338  51.3807
26  2021-04-09  707.7100  708.1600  667.8400  677.0200  141785455  53.6202
27  2021-04-01  615.6400  692.4203  591.0100  661.7500  136705010  44.5156
28  2021-03-26  684.5900  699.6200  599.8900  618.7100  176876942  51.3035
29  2021-03-19  694.0900  713.1800  624.6201  654.8700  178254604  52.2923
30  2021-03-12  600.5500  717.8500  558.7900  693.7300  249753690  42.4660
31  2021-03-05  690.1100  721.1100  539.4900  597.9500  235272714  51.6294
32  2021-02-26  762.6400  768.5000  619.0000  675.5000  217862425  61.2647
33  2021-02-19  818.0000  821.0000  762.0100  781.3000   82596163  70.2740
34  2021-02-12  869.6700  877.7700  785.3306  816.1200  116303534  80.1781
35  2021-02-05  814.2900  880.5000  795.5601  852.2300  102112291  77.0593
36  2021-01-29  855.0000  900.4000  780.1000  793.5300  153007757  86.0128
37  2021-01-22  837.8000  859.5000  828.6200  846.6400   91697493  85.3663
38  2021-01-15  849.4000  868.0000  803.6222  826.1600  208896134  87.8305
39  2021-01-08  719.4600  884.4900  717.1895  880.0200  252137795  82.8353
40  2020-12-31  674.5100  718.7200  655.0000  705.6700  146960321  80.3203
41  2020-12-24  666.2400  668.5000  614.2300  661.7700  165945448  79.8309
42  2020-12-18  619.0000  695.0000  605.0000  695.0000  417756359  76.8749
43  2020-12-11  604.9197  654.3200  566.3400  609.9900  305424055  75.9285
44  2020-12-04  602.2100  607.8000  541.2100  599.0400  221865368  75.7566
45  2020-11-27  503.5000  598.7800  501.7900  585.7600  188810315  68.3484
46  2020-11-20  408.9300  508.6112  404.0868  489.6100  261458208  57.0252
47  2020-11-13  439.5000  452.5000  396.0301  408.5000  122245822  63.6497
48  2020-11-06  394.0000  440.0000  392.3000  429.9500  145636427  56.9507
49  2020-10-30  411.6300  430.5000  379.1100  388.0400  141620023  60.8621

In [16]:
merged_weekly_rsi = merged_weekly_rsi.rename(columns={'index': 'Date', '1. open': 'Open', '2. high': 'High', '3. low': 'Low', '4. close': 'Close', '5. volume': 'Volume'})

merged_weekly_rsi

           Date      Open      High       Low     Close     Volume      RSI
0    2021-10-08  796.5000  806.9699  773.2200  785.4900   99483120  69.5571
1    2021-10-01  773.1200  799.0000  763.5900  775.2200  109382331  66.4242
2    2021-09-24  734.5577  774.8000  718.6249  774.3900   89535196  60.3699
3    2021-09-17  740.2143  761.0400  708.8500  759.4900   98962617  61.8421
4    2021-09-10  740.0000  764.4500  734.5201  736.2700   68094762  61.8103
..          ...       ...       ...       ...       ...        ...      ...
573  2010-10-15   20.4400   21.0299   20.0300   20.5400    1312900  51.5720
574  2010-10-08   20.4300   21.2800   20.3000   20.4300    1697800  51.5090
575  2010-10-01   20.4000   22.1499   20.0500   20.6000    6395900  51.3380
576  2010-09-24   20.6700   21.5500   19.5000   20.1000    3953400  52.8478
577  2010-09-17   20.8900   23.1600   19.8000   20.2300    5583100  54.0126

[578 rows x 7 columns]

In [18]:
merged_weekly_rsi.dropna()

           Date      Open      High       Low     Close     Volume      RSI
0    2021-10-08  796.5000  806.9699  773.2200  785.4900   99483120  69.5571
1    2021-10-01  773.1200  799.0000  763.5900  775.2200  109382331  66.4242
2    2021-09-24  734.5577  774.8000  718.6249  774.3900   89535196  60.3699
3    2021-09-17  740.2143  761.0400  708.8500  759.4900   98962617  61.8421
4    2021-09-10  740.0000  764.4500  734.5201  736.2700   68094762  61.8103
..          ...       ...       ...       ...       ...        ...      ...
573  2010-10-15   20.4400   21.0299   20.0300   20.5400    1312900  51.5720
574  2010-10-08   20.4300   21.2800   20.3000   20.4300    1697800  51.5090
575  2010-10-01   20.4000   22.1499   20.0500   20.6000    6395900  51.3380
576  2010-09-24   20.6700   21.5500   19.5000   20.1000    3953400  52.8478
577  2010-09-17   20.8900   23.1600   19.8000   20.2300    5583100  54.0126

[578 rows x 7 columns]

In [35]:
merged_weekly_rsi_adjusted = merged_weekly_rsi[['Date', 'Close', 'RSI']]
merged_weekly_rsi_adjusted

           Date     Close      RSI
0    2021-10-08  785.4900  69.5571
1    2021-10-01  775.2200  66.4242
2    2021-09-24  774.3900  60.3699
3    2021-09-17  759.4900  61.8421
4    2021-09-10  736.2700  61.8103
..          ...       ...      ...
573  2010-10-15   20.5400  51.5720
574  2010-10-08   20.4300  51.5090
575  2010-10-01   20.6000  51.3380
576  2010-09-24   20.1000  52.8478
577  2010-09-17   20.2300  54.0126

[578 rows x 3 columns]

In [41]:
merged_weekly_rsi_adjusted = merged_weekly_rsi_adjusted.sort_values('Date', ascending = True)
merged_weekly_rsi_adjusted.head(50)

           Date   Close      RSI
577  2010-09-17  20.230  54.0126
576  2010-09-24  20.100  52.8478
575  2010-10-01  20.600  51.3380
574  2010-10-08  20.430  51.5090
573  2010-10-15  20.540  51.5720
572  2010-10-22  20.720  52.1253
571  2010-10-29  21.840  55.1162
570  2010-11-05  24.440  61.4823
569  2010-11-12  29.840  72.5549
568  2010-11-19  30.990  83.9846
567  2010-11-26  35.320  85.5615
566  2010-12-03  31.490  88.9896
565  2010-12-10  31.520  69.5820
564  2010-12-17  31.360  70.0993
563  2010-12-23  30.090  70.0993
562  2010-12-31  26.630  55.5435
561  2011-01-07  28.240  51.6584
560  2011-01-14  25.750  55.5519
559  2011-01-21  23.040  47.0380
558  2011-01-28  24.010  41.8695
557  2011-02-04  23.460  43.7024
556  2011-02-11  23.250  41.4939
555  2011-02-18  23.180  43.0325
554  2011-02-25  23.610  40.6565
553  2011-03-04  24.950  44.5088
552  2011-03-11  24.070  49.5445
551  2011-03-18  22.960  45.2853
550  2011-03-25  22.750  42.4711
549  2011-04-01  26.660  41.1787
548  2011-04-08  26.490  57.9540
547  2011-04-15  25.580  56.3963
546  2011-04-21  26.740  50.7541
545  2011-04-29  27.600  56.4289
544  2011-05-06  27.120  59.4082
543  2011-05-13  27.550  56.5442
542  2011-05-20  27.970  60.0730
541  2011-05-27  29.550  58.1133
540  2011-06-03  30.130  65.1752
539  2011-06-10  27.860  61.8717
538  2011-06-17  26.500  56.3331
537  2011-06-24  27.565  48.0704
536  2011-07-01  29.020  54.1195
535  2011-07-08  28.810  58.8864
534  2011-07-15  27.580  55.7909
533  2011-07-22  29.290  50.7254
532  2011-07-29  28.170  57.4829
531  2011-08-05  24.240  55.7533
530  2011-08-12  26.310  36.0231
529  2011-08-19  22.300  48.7565
528  2011-08-26  23.730  39.9474

In [37]:
merged_weekly_rsi_adjusted.dtypes

Date     object
Close    object
RSI      object
dtype: object

In [38]:
merged_weekly_rsi_adjusted['Close'] = pd.to_numeric(merged_weekly_rsi_adjusted['Close'], errors='coerce')

In [39]:
merged_weekly_rsi_adjusted['RSI'] = pd.to_numeric(merged_weekly_rsi_adjusted['RSI'], errors='coerce')

In [40]:
merged_weekly_rsi_adjusted.dtypes

Date      object
Close    float64
RSI      float64
dtype: object

In [42]:
merged_weekly_rsi_adjusted['Buy'] = (merged_weekly_rsi_adjusted['RSI'] < 30) & (merged_weekly_rsi_adjusted['RSI'].shift(periods = 1) > 30)

In [43]:
merged_weekly_rsi_adjusted['Sell'] = (merged_weekly_rsi_adjusted['RSI'] > 70) & (merged_weekly_rsi_adjusted['RSI'].shift(periods = 1) < 70)

In [46]:
merged_weekly_rsi_adjusted.head(50)

           Date   Close      RSI    Buy   Sell
577  2010-09-17  20.230  54.0126  False  False
576  2010-09-24  20.100  52.8478  False  False
575  2010-10-01  20.600  51.3380  False  False
574  2010-10-08  20.430  51.5090  False  False
573  2010-10-15  20.540  51.5720  False  False
572  2010-10-22  20.720  52.1253  False  False
571  2010-10-29  21.840  55.1162  False  False
570  2010-11-05  24.440  61.4823  False  False
569  2010-11-12  29.840  72.5549  False   True
568  2010-11-19  30.990  83.9846  False  False
567  2010-11-26  35.320  85.5615  False  False
566  2010-12-03  31.490  88.9896  False  False
565  2010-12-10  31.520  69.5820  False  False
564  2010-12-17  31.360  70.0993  False   True
563  2010-12-23  30.090  70.0993  False  False
562  2010-12-31  26.630  55.5435  False  False
561  2011-01-07  28.240  51.6584  False  False
560  2011-01-14  25.750  55.5519  False  False
559  2011-01-21  23.040  47.0380  False  False
558  2011-01-28  24.010  41.8695  False  False
557  2011-02-04  23.460  43.7024  False  False
556  2011-02-11  23.250  41.4939  False  False
555  2011-02-18  23.180  43.0325  False  False
554  2011-02-25  23.610  40.6565  False  False
553  2011-03-04  24.950  44.5088  False  False
552  2011-03-11  24.070  49.5445  False  False
551  2011-03-18  22.960  45.2853  False  False
550  2011-03-25  22.750  42.4711  False  False
549  2011-04-01  26.660  41.1787  False  False
548  2011-04-08  26.490  57.9540  False  False
547  2011-04-15  25.580  56.3963  False  False
546  2011-04-21  26.740  50.7541  False  False
545  2011-04-29  27.600  56.4289  False  False
544  2011-05-06  27.120  59.4082  False  False
543  2011-05-13  27.550  56.5442  False  False
542  2011-05-20  27.970  60.0730  False  False
541  2011-05-27  29.550  58.1133  False  False
540  2011-06-03  30.130  65.1752  False  False
539  2011-06-10  27.860  61.8717  False  False
538  2011-06-17  26.500  56.3331  False  False
537  2011-06-24  27.565  48.0704  False  False
536  2011-07-01  29.020  54.1195  False  False
535  2011-07-08  28.810  58.8864  False  False
534  2011-07-15  27.580  55.7909  False  False
533  2011-07-22  29.290  50.7254  False  False
532  2011-07-29  28.170  57.4829  False  False
531  2011-08-05  24.240  55.7533  False  False
530  2011-08-12  26.310  36.0231  False  False
529  2011-08-19  22.300  48.7565  False  False
528  2011-08-26  23.730  39.9474  False  False

In [49]:
df = merged_weekly_rsi_adjusted[(merged_weekly_rsi_adjusted['Sell'] == True) | (merged_weekly_rsi_adjusted['Buy'] == True)] 
df = df.reset_index()
df

    index        Date   Close      RSI    Buy   Sell
0     569  2010-11-12   29.84  72.5549  False   True
1     564  2010-12-17   31.36  70.0993  False   True
2     496  2012-04-05   34.48  72.6258  False   True
3     452  2013-02-08   39.24  71.8476  False   True
4     441  2013-04-26   51.20  76.3621  False   True
5     415  2013-10-25  169.66  71.2396  False   True
6     399  2014-02-14  198.23  70.6555  False   True
7     373  2014-08-15  262.01  70.4449  False   True
8     370  2014-09-05  277.39  74.1420  False   True
9     328  2015-06-26  267.09  73.0533  False   True
10    295  2016-02-12  151.04  25.3042   True  False
11    245  2017-01-27  252.95  72.3934  False   True
12    235  2017-04-07  302.54  73.2881  False   True
13    183  2018-04-06  299.30  28.6197   True  False
14    124  2019-05-24  190.63  26.8387   True  False
15    101  2019-11-01  313.31  75.9738  False   True
16     94  2019-12-20  405.59  72.4216  False   True
17     70  2020-06-05  885.66  70.9163  False   True
18     54  2020-09-25  407.34  72.9377  False   True
19     44  2020-12-04  599.04  75.7566  False   True

In [ ]:
for i in df.itterrows():
    
    row['Sell'] == True

In [50]:
import numpy as np

In [51]:
cap = 10000
shares = 0
cap_list = []
share_list = []
df_test = df.copy()

for i, row in df_test.iterrows():
    if row['Sell']:
        #print("sell")
        cap = shares * row['Close']
        shares = 0
        #print(f"1 cap = {cap} \t shares={shares}")

        cap_list.append(cap)
        share_list.append(0)
    else:
        #print("buy")
        shares = cap / row['Close']
        cap = 0
        #print(f"2 cap = {cap} \t shares={shares}")

        cap_list.append(0)
        share_list.append(shares)

    if cap < 0:
        print("BROKE!!!")
        break

if cap >= 0:
    df_test['capital'] = cap_list
    df_test['shares'] = share_list

df_test

    index        Date   Close      RSI    Buy   Sell  capital  shares
0     569  2010-11-12   29.84  72.5549  False   True      0.0     0.0
1     564  2010-12-17   31.36  70.0993  False   True      0.0     0.0
2     496  2012-04-05   34.48  72.6258  False   True      0.0     0.0
3     452  2013-02-08   39.24  71.8476  False   True      0.0     0.0
4     441  2013-04-26   51.20  76.3621  False   True      0.0     0.0
5     415  2013-10-25  169.66  71.2396  False   True      0.0     0.0
6     399  2014-02-14  198.23  70.6555  False   True      0.0     0.0
7     373  2014-08-15  262.01  70.4449  False   True      0.0     0.0
8     370  2014-09-05  277.39  74.1420  False   True      0.0     0.0
9     328  2015-06-26  267.09  73.0533  False   True      0.0     0.0
10    295  2016-02-12  151.04  25.3042   True  False      0.0     0.0
11    245  2017-01-27  252.95  72.3934  False   True      0.0     0.0
12    235  2017-04-07  302.54  73.2881  False   True      0.0     0.0
13    183  2018-04-06  299.30  28.6197   True  False      0.0     0.0
14    124  2019-05-24  190.63  26.8387   True  False      0.0     0.0
15    101  2019-11-01  313.31  75.9738  False   True      0.0     0.0
16     94  2019-12-20  405.59  72.4216  False   True      0.0     0.0
17     70  2020-06-05  885.66  70.9163  False   True      0.0     0.0
18     54  2020-09-25  407.34  72.9377  False   True      0.0     0.0
19     44  2020-12-04  599.04  75.7566  False   True      0.0     0.0

In [52]:
df_test

    index        Date   Close      RSI    Buy   Sell  capital  shares
0     569  2010-11-12   29.84  72.5549  False   True      0.0     0.0
1     564  2010-12-17   31.36  70.0993  False   True      0.0     0.0
2     496  2012-04-05   34.48  72.6258  False   True      0.0     0.0
3     452  2013-02-08   39.24  71.8476  False   True      0.0     0.0
4     441  2013-04-26   51.20  76.3621  False   True      0.0     0.0
5     415  2013-10-25  169.66  71.2396  False   True      0.0     0.0
6     399  2014-02-14  198.23  70.6555  False   True      0.0     0.0
7     373  2014-08-15  262.01  70.4449  False   True      0.0     0.0
8     370  2014-09-05  277.39  74.1420  False   True      0.0     0.0
9     328  2015-06-26  267.09  73.0533  False   True      0.0     0.0
10    295  2016-02-12  151.04  25.3042   True  False      0.0     0.0
11    245  2017-01-27  252.95  72.3934  False   True      0.0     0.0
12    235  2017-04-07  302.54  73.2881  False   True      0.0     0.0
13    183  2018-04-06  299.30  28.6197   True  False      0.0     0.0
14    124  2019-05-24  190.63  26.8387   True  False      0.0     0.0
15    101  2019-11-01  313.31  75.9738  False   True      0.0     0.0
16     94  2019-12-20  405.59  72.4216  False   True      0.0     0.0
17     70  2020-06-05  885.66  70.9163  False   True      0.0     0.0
18     54  2020-09-25  407.34  72.9377  False   True      0.0     0.0
19     44  2020-12-04  599.04  75.7566  False   True      0.0     0.0