In [1]:
import pandas as pd
import requests

In [2]:
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=GOOG&apikey=PLWHFCZSI5GFFUMN'
r = requests.get(url)
google_weekly_data = r.json()

print(google_weekly_data)

{'Meta Data': {'1. Information': 'Weekly Prices (open, high, low, close) and Volumes', '2. Symbol': 'GOOG', '3. Last Refreshed': '2021-10-08', '4. Time Zone': 'US/Eastern'}, 'Weekly Time Series': {'2021-10-08': {'1. open': '2713.9900', '2. high': '2806.3400', '3. low': '2623.3300', '4. close': '2801.1200', '5. volume': '5629992'}, '2021-10-01': {'1. open': '2831.7100', '2. high': '2850.0000', '3. low': '2660.0000', '4. close': '2729.2500', '5. volume': '7556112'}, '2021-09-24': {'1. open': '2780.0035', '2. high': '2858.0700', '3. low': '2741.0600', '4. close': '2852.6600', '5. volume': '5367017'}, '2021-09-17': {'1. open': '2864.0200', '2. high': '2911.6300', '3. low': '2821.2300', '4. close': '2829.2700', '5. volume': '7004342'}, '2021-09-10': {'1. open': '2894.9900', '2. high': '2920.3800', '3. low': '2834.8300', '4. close': '2838.4200', '5. volume': '3917972'}, '2021-09-03': {'1. open': '2894.0900', '2. high': '2936.4099', '3. low': '2870.1000', '4. close': '2895.5000', '5. volume': '5023164'}, '2021-08-27': {'1. open': '2779.9700', '2. high': '2900.2200', '3. low': '2774.9586', '4. close': '2891.0100', '5. volume': '4427462'}, '2021-08-20': {'1. open': '2760.0000', '2. high': '2779.8100', '3. low': '2707.1200', '4. close': '2768.7400', '5. volume': '4406099'}, '2021-08-13': {'1. open': '2738.9800', '2. high': '2776.9550', '3. low': '2728.5750', '4. close': '2768.1200', '5. volume': '3540233'}, '2021-08-06': {'1. open': '2709.6900', '2. high': '2741.6009', '3. low': '2683.6700', '4. close': '2740.7200', '5. volume': '4058399'}, '2021-07-30': {'1. open': '2765.0000', '2. high': '2800.2200', '3. low': '2696.2840', '4. close': '2704.4200', '5. volume': '8141483'}, '2021-07-23': {'1. open': '2623.1100', '2. high': '2776.1700', '3. low': '2570.7400', '4. close': '2756.3200', '5. volume': '4975998'}, '2021-07-16': {'1. open': '2596.6700', '2. high': '2659.9199', '3. low': '2592.0000', '4. close': '2636.9100', '5. volume': '4146746'}, '2021-07-09': {'1. open': '2588.9900', '2. high': '2612.7983', '3. low': '2560.8000', '4. close': '2591.4900', '5. volume': '3646144'}, '2021-07-02': {'1. open': '2540.0000', '2. high': '2576.9600', '3. low': '2495.1500', '4. close': '2574.3800', '5. volume': '5567985'}, '2021-06-25': {'1. open': '2514.8000', '2. high': '2555.9200', '3. low': '2502.6850', '4. close': '2539.9000', '5. volume': '5967753'}, '2021-06-18': {'1. open': '2513.3900', '2. high': '2543.9300', '3. low': '2482.9994', '4. close': '2511.3500', '5. volume': '7496921'}, '2021-06-11': {'1. open': '2451.3200', '2. high': '2526.9900', '3. low': '2441.0725', '4. close': '2513.9300', '5. volume': '6276085'}, '2021-06-04': {'1. open': '2422.0000', '2. high': '2453.8590', '3. low': '2382.8300', '4. close': '2451.7600', '5. volume': '4031119'}, '2021-05-28': {'1. open': '2367.0000', '2. high': '2442.9440', '3. low': '2360.1100', '4. close': '2411.5600', '5. volume': '6250431'}, '2021-05-21': {'1. open': '2309.3200', '2. high': '2368.9999', '3. low': '2263.5200', '4. close': '2345.1000', '5. volume': '5158304'}, '2021-05-14': {'1. open': '2374.8900', '2. high': '2378.0000', '3. low': '2230.0500', '4. close': '2316.1600', '5. volume': '7317239'}, '2021-05-07': {'1. open': '2402.7200', '2. high': '2419.7000', '3. low': '2311.7000', '4. close': '2398.6900', '5. volume': '6730430'}, '2021-04-30': {'1. open': '2319.9300', '2. high': '2452.3780', '3. low': '2304.2700', '4. close': '2410.1200', '5. volume': '9561479'}, '2021-04-23': {'1. open': '2291.9800', '2. high': '2325.8200', '3. low': '2256.4500', '4. close': '2315.3000', '5. volume': '6009895'}, '2021-04-16': {'1. open': '2266.2500', '2. high': '2306.5965', '3. low': '2238.4650', '4. close': '2297.7600', '5. volume': '6246324'}, '2021-04-09': {'1. open': '2152.9400', '2. high': '2289.0400', '3. low': '2151.6200', '4. close': '2285.8800', '5. volume': '7210396'}, '2021-04-01': {'1. open': '2027.8800', '2. high': '2142.9400', '3. low': '2015.6200', '4. close': '2137.7500', '5. volume': '5425459'}, '2021-03-26': {'1. open': '2041.8400', '2. high': '2078.2100', '3. low': '2010.7300', '4. close': '2035.5500', '5. volume': '7388549'}, '2021-03-19': {'1. open': '2062.3000', '2. high': '2123.5600', '3. low': '2017.6800', '4. close': '2043.2000', '5. volume': '7766228'}, '2021-03-12': {'1. open': '2101.1300', '2. high': '2128.8100', '3. low': '2021.6100', '4. close': '2061.9200', '5. volume': '7578201'}, '2021-03-05': {'1. open': '2056.5200', '2. high': '2118.1100', '3. low': '2010.0000', '4. close': '2108.5400', '5. volume': '8337115'}, '2021-02-26': {'1. open': '2067.0000', '2. high': '2100.7800', '3. low': '2002.0200', '4. close': '2036.8600', '5. volume': '8103757'}, '2021-02-19': {'1. open': '2104.3600', '2. high': '2152.6800', '3. low': '2097.4100', '4. close': '2101.1400', '5. volume': '4733557'}, '2021-02-12': {'1. open': '2105.9100', '2. high': '2123.5469', '3. low': '2063.0900', '4. close': '2104.1100', '5. volume': '5062914'}, '2021-02-05': {'1. open': '1853.5700', '2. high': '2116.5000', '3. low': '1850.9300', '4. close': '2098.0000', '5. volume': '11211680'}, '2021-01-29': {'1. open': '1920.6700', '2. high': '1929.5800', '3. low': '1809.0000', '4. close': '1835.7400', '5. volume': '9374441'}, '2021-01-22': {'1. open': '1752.2500', '2. high': '1934.8600', '3. low': '1741.4600', '4. close': '1901.0500', '5. volume': '7561036'}, '2021-01-15': {'1. open': '1786.0700', '2. high': '1794.3150', '3. low': '1721.5500', '4. close': '1736.1900', '5. volume': '6181977'}, '2021-01-08': {'1. open': '1757.5400', '2. high': '1809.8400', '3. low': '1699.0000', '4. close': '1807.2100', '5. volume': '9965340'}, '2020-12-31': {'1. open': '1751.6350', '2. high': '1792.4400', '3. low': '1725.6000', '4. close': '1751.8800', '5. volume': '5008727'}, '2020-12-24': {'1. open': '1713.5100', '2. high': '1747.9900', '3. low': '1699.0000', '4. close': '1738.8500', '5. volume': '4147394'}, '2020-12-18': {'1. open': '1775.0000', '2. high': '1797.3900', '3. low': '1720.2200', '4. close': '1731.0100', '5. volume': '10237074'}, '2020-12-11': {'1. open': '1819.0000', '2. high': '1834.2700', '3. low': '1740.3200', '4. close': '1781.7700', '5. volume': '6508322'}, '2020-12-04': {'1. open': '1781.1844', '2. high': '1847.2000', '3. low': '1755.0000', '4. close': '1827.9900', '5. volume': '7344925'}, '2020-11-27': {'1. open': '1749.6000', '2. high': '1804.0000', '3. low': '1717.7200', '4. close': '1793.1900', '5. volume': '5584711'}, '2020-11-20': {'1. open': '1771.7000', '2. high': '1799.0700', '3. low': '1737.0050', '4. close': '1742.1900', '5. volume': '7130930'}, '2020-11-13': {'1. open': '1790.9000', '2. high': '1818.0600', '3. low': '1717.3000', '4. close': '1777.0200', '5. volume': '8917706'}, '2020-11-06': {'1. open': '1628.1600', '2. high': '1793.6400', '3. low': '1616.0300', '4. close': '1761.7500', '5. volume': '11495063'}, '2020-10-30': {'1. open': '1625.0100', '2. high': '1687.0000', '3. low': '1514.6200', '4. close': '1621.0100', '5. volume': '11250141'}, '2020-10-23': {'1. open': '1580.4600', '2. high': '1642.3600', '3. low': '1525.6700', '4. close': '1641.0000', '5. volume': '9227878'}, '2020-10-16': {'1. open': '1543.0000', '2. high': '1593.8600', '3. low': '1532.5700', '4. close': '1573.0100', '5. volume': '8990547'}, '2020-10-09': {'1. open': '1466.2100', '2. high': '1516.5200', '3. low': '1436.0000', '4. close': '1515.2200', '5. volume': '6728209'}, '2020-10-02': {'1. open': '1474.2100', '2. high': '1499.0400', '3. low': '1449.3012', '4. close': '1458.4200', '5. volume': '7752219'}, '2020-09-25': {'1. open': '1440.0600', '2. high': '1469.5200', '3. low': '1406.5500', '4. close': '1444.9600', '5. volume': '8902969'}, '2020-09-18': {'1. open': '1539.0050', '2. high': '1563.9999', '3. low': '1437.1300', '4. close': '1459.9900', '5. volume': '9323603'}, '2020-09-11': {'1. open': '1533.5100', '2. high': '1584.0810', '3. low': '1497.3600', '4. close': '1520.7200', '5. volume': '7601232'}, '2020-09-04': {'1. open': '1647.8900', '2. high': '1733.1799', '3. low': '1547.6125', '4. close': '1591.0400', '5. volume': '11877572'}, '2020-08-28': {'1. open': '1593.9800', '2. high': '1659.2200', '3. low': '1580.5700', '4. close': '1644.4100', '5. volume': '10484769'}, '2020-08-21': {'1. open': '1514.6700', '2. high': '1597.7200', '3. low': '1507.9700', '4. close': '1580.4200', '5. volume': '8205109'}, '2020-08-14': {'1. open': '1487.1800', '2. high': '1537.2500', '3. low': '1473.0800', '4. close': '1507.7300', '5. volume': '6991958'}, '2020-08-07': {'1. open': '1486.6400', '2. high': '1516.8450', '3. low': '1458.6500', '4. close': '1494.4900', '5. volume': '9788154'}, '2020-07-31': {'1. open': '1515.6000', '2. high': '1540.9700', '3. low': '1454.0300', '4. close': '1482.9600', '5. volume': '9155120'}, '2020-07-24': {'1. open': '1515.2600', '2. high': '1586.9900', '3. low': '1488.4000', '4. close': '1511.8700', '5. volume': '6834260'}, '2020-07-17': {'1. open': '1550.0000', '2. high': '1577.1300', '3. low': '1483.5000', '4. close': '1515.5500', '5. volume': '8168700'}, '2020-07-10': {'1. open': '1480.0600', '2. high': '1543.8300', '3. low': '1472.8600', '4. close': '1541.7400', '5. volume': '7552400'}, '2020-07-02': {'1. open': '1358.1800', '2. high': '1482.9500', '3. low': '1347.0100', '4. close': '1464.7000', '5. volume': '7488000'}, '2020-06-26': {'1. open': '1429.0000', '2. high': '1475.9400', '3. low': '1351.9900', '4. close': '1359.9000', '5. volume': '10226398'}, '2020-06-19': {'1. open': '1390.8000', '2. high': '1460.0000', '3. low': '1387.9200', '4. close': '1431.7200', '5. volume': '9507116'}, '2020-06-12': {'1. open': '1422.3400', '2. high': '1474.2600', '3. low': '1386.0200', '4. close': '1413.1800', '5. volume': '8276279'}, '2020-06-05': {'1. open': '1418.3900', '2. high': '1446.5500', '3. low': '1404.7300', '4. close': '1438.3900', '5. volume': '6970970'}, '2020-05-29': {'1. open': '1437.2700', '2. high': '1441.0000', '3. low': '1391.2900', '4. close': '1428.9200', '5. volume': '7278820'}, '2020-05-22': {'1. open': '1361.7500', '2. high': '1415.4900', '3. low': '1354.2500', '4. close': '1410.4200', '5. volume': '7447416'}, '2020-05-15': {'1. open': '1378.2800', '2. high': '1416.5300', '3. low': '1323.9100', '4. close': '1373.1900', '5. volume': '7926125'}, '2020-05-08': {'1. open': '1308.2300', '2. high': '1398.7600', '3. low': '1299.0000', '4. close': '1388.3700', '5. volume': '7158800'}, '2020-05-01': {'1. open': '1296.0000', '2. high': '1359.9900', '3. low': '1232.2000', '4. close': '1320.6100', '5. volume': '13087047'}, '2020-04-24': {'1. open': '1271.0000', '2. high': '1293.3100', '3. low': '1209.7100', '4. close': '1279.3100', '5. volume': '9148228'}, '2020-04-17': {'1. open': '1209.1800', '2. high': '1294.4300', '3. low': '1187.6000', '4. close': '1283.2500', '5. volume': '10349025'}, '2020-04-09': {'1. open': '1138.0000', '2. high': '1225.5700', '3. low': '1130.9400', '4. close': '1211.4500', '5. volume': '9202608'}, '2020-04-03': {'1. open': '1125.0400', '2. high': '1175.3100', '3. low': '1079.8100', '4. close': '1097.8800', '5. volume': '11684498'}, '2020-03-27': {'1. open': '1061.3200', '2. high': '1169.9700', '3. low': '1013.5400', '4. close': '1110.7100', '5. volume': '18252365'}, '2020-03-20': {'1. open': '1096.0000', '2. high': '1157.9700', '3. low': '1037.2800', '4. close': '1072.3200', '5. volume': '19600145'}, '2020-03-13': {'1. open': '1205.3000', '2. high': '1281.1500', '3. low': '1113.3000', '4. close': '1219.7300', '5. volume': '16514840'}, '2020-03-06': {'1. open': '1351.6100', '2. high': '1410.1500', '3. low': '1261.0500', '4. close': '1298.4100', '5. volume': '11969025'}, '2020-02-28': {'1. open': '1426.1100', '2. high': '1438.1400', '3. low': '1271.0000', '4. close': '1339.3300', '5. volume': '14318286'}, '2020-02-21': {'1. open': '1515.0000', '2. high': '1532.1100', '3. low': '1480.4400', '4. close': '1485.1100', '5. volume': '4899233'}, '2020-02-14': {'1. open': '1474.3200', '2. high': '1529.6300', '3. low': '1474.3200', '4. close': '1520.7400', '5. volume': '6059640'}, '2020-02-07': {'1. open': '1462.0000', '2. high': '1490.0000', '3. low': '1426.3000', '4. close': '1479.2300', '5. volume': '11825981'}, '2020-01-31': {'1. open': '1431.0000', '2. high': '1470.1300', '3. low': '1421.2000', '4. close': '1434.2300', '5. volume': '8167925'}, '2020-01-24': {'1. open': '1479.1200', '2. high': '1503.2100', '3. low': '1465.2500', '4. close': '1466.7100', '5. volume': '6755674'}, '2020-01-17': {'1. open': '1436.1300', '2. high': '1481.3000', '3. low': '1426.0200', '4. close': '1480.3900', '5. volume': '7791327'}, '2020-01-10': {'1. open': '1350.0000', '2. high': '1434.9300', '3. low': '1350.0000', '4. close': '1429.7300', '5. volume': '8098249'}, '2020-01-03': {'1. open': '1350.0000', '2. high': '1372.5000', '3. low': '1329.0900', '4. close': '1360.6600', '5. volume': '4607528'}, '2019-12-27': {'1. open': '1355.8700', '2. high': '1364.5300', '3. low': '1342.7800', '4. close': '1351.8900', '5. volume': '2937190'}, '2019-12-20': {'1. open': '1356.5000', '2. high': '1365.0000', '3. low': '1348.9800', '4. close': '1349.5900', '5. volume': '9696796'}, '2019-12-13': {'1. open': '1338.0400', '2. high': '1359.4500', '3. low': '1336.0400', '4. close': '1347.8300', '5. volume': '6132994'}, '2019-12-06': {'1. open': '1301.0000', '2. high': '1344.0000', '3. low': '1279.0000', '4. close': '1340.6200', '5. volume': '6846936'}, '2019-11-29': {'1. open': '1299.1800', '2. high': '1318.3600', '3. low': '1298.1300', '4. close': '1304.9600', '5. volume': '3689592'}, '2019-11-22': {'1. open': '1332.2200', '2. high': '1335.5300', '3. low': '1291.1500', '4. close': '1295.3400', '5. volume': '6449295'}, '2019-11-15': {'1. open': '1303.1800', '2. high': '1334.8800', '3. low': '1293.5100', '4. close': '1334.8700', '5. volume': '5929409'}, '2019-11-08': {'1. open': '1276.4500', '2. high': '1323.7400', '3. low': '1276.3600', '4. close': '1311.3700', '5. volume': '7218538'}, '2019-11-01': {'1. open': '1275.4500', '2. high': '1299.3100', '3. low': '1250.8400', '4. close': '1273.7400', '5. volume': '8945930'}, '2019-10-25': {'1. open': '1252.2600', '2. high': '1269.6000', '3. low': '1240.6000', '4. close': '1265.1300', '5. volume': '5256115'}, '2019-10-18': {'1. open': '1212.3400', '2. high': '1263.3300', '3. low': '1211.7600', '4. close': '1245.4900', '5. volume': '5747906'}, '2019-10-11': {'1. open': '1204.4000', '2. high': '1228.3900', '3. low': '1189.0100', '4. close': '1215.4500', '5. volume': '5095240'}, '2019-10-04': {'1. open': '1220.9700', '2. high': '1231.2300', '3. low': '1162.4300', '4. close': '1209.0000', '5. volume': '7264112'}, '2019-09-27': {'1. open': '1226.0000', '2. high': '1248.3000', '3. low': '1210.0900', '4. close': '1225.0900', '5. volume': '7177228'}, '2019-09-20': {'1. open': '1229.5200', '2. high': '1244.4400', '3. low': '1216.5300', '4. close': '1229.9300', '5. volume': '6493168'}, '2019-09-13': {'1. open': '1204.0000', '2. high': '1241.8600', '3. low': '1192.6200', '4. close': '1239.5600', '5. volume': '7066286'}, '2019-09-06': {'1. open': '1177.0300', '2. high': '1213.0400', '3. low': '1163.2000', '4. close': '1204.9300', '5. volume': '5030132'}, '2019-08-30': {'1. open': '1157.2600', '2. high': '1198.5000', '3. low': '1152.9600', '4. close': '1188.1000', '5. volume': '5293625'}, '2019-08-23': {'1. open': '1190.0900', '2. high': '1206.9900', '3. low': '1147.7500', '4. close': '1151.2900', '5. volume': '5525352'}, '2019-08-16': {'1. open': '1179.2100', '2. high': '1204.7800', '3. low': '1160.5400', '4. close': '1177.6000', '5. volume': '6474039'}, '2019-08-09': {'1. open': '1170.0400', '2. high': '1205.0100', '3. low': '1140.1400', '4. close': '1188.0100', '5. volume': '8284808'}, '2019-08-02': {'1. open': '1241.0500', '2. high': '1247.3700', '3. low': '1188.9400', '4. close': '1193.9900', '5. volume': '8746025'}, '2019-07-26': {'1. open': '1133.4500', '2. high': '1265.5500', '3. low': '1120.9200', '4. close': '1250.4100', '5. volume': '11001268'}, '2019-07-19': {'1. open': '1146.8600', '2. high': '1158.5800', '3. low': '1129.6200', '4. close': '1130.1000', '5. volume': '6251160'}, '2019-07-12': {'1. open': '1125.1700', '2. high': '1153.0700', '3. low': '1107.1700', '4. close': '1144.9000', '5. volume': '5835797'}, '2019-07-05': {'1. open': '1098.0000', '2. high': '1132.8800', '3. low': '1093.7000', '4. close': '1131.5900', '5. volume': '4461810'}, '2019-06-28': {'1. open': '1119.6100', '2. high': '1122.0000', '3. low': '1072.2400', '4. close': '1080.9100', '5. volume': '7451405'}, '2019-06-21': {'1. open': '1086.2800', '2. high': '1124.1100', '3. low': '1086.2800', '4. close': '1121.8800', '5. volume': '6877106'}, '2019-06-14': {'1. open': '1072.9800', '2. high': '1101.9900', '3. low': '1067.5400', '4. close': '1085.3500', '5. volume': '6132209'}, '2019-06-07': {'1. open': '1065.5000', '2. high': '1070.9200', '3. low': '1025.0000', '4. close': '1066.0400', '5. volume': '13638112'}, '2019-05-31': {'1. open': '1134.0000', '2. high': '1151.5900', '3. low': '1100.1800', '4. close': '1103.6300', '5. volume': '5363454'}, '2019-05-24': {'1. open': '1144.5000', '2. high': '1158.5200', '3. low': '1129.2200', '4. close': '1133.4700', '5. volume': '5739930'}, '2019-05-17': {'1. open': '1141.9600', '2. high': '1188.1600', '3. low': '1116.6700', '4. close': '1162.3000', '5. volume': '8726581'}, '2019-05-10': {'1. open': '1166.2600', '2. high': '1190.8500', '3. low': '1142.5000', '4. close': '1164.2700', '5. volume': '6925344'}, '2019-05-03': {'1. open': '1274.0000', '2. high': '1289.2700', '3. low': '1155.0000', '4. close': '1185.4000', '5. volume': '15274912'}, '2019-04-26': {'1. open': '1235.9900', '2. high': '1273.0700', '3. low': '1228.3100', '4. close': '1272.1800', '5. volume': '5494720'}, '2019-04-18': {'1. open': '1218.0000', '2. high': '1242.0000', '3. low': '1209.1100', '4. close': '1236.3700', '5. volume': '4597576'}, '2019-04-12': {'1. open': '1207.8900', '2. high': '1218.3500', '3. low': '1193.0800', '4. close': '1217.8700', '5. volume': '4105412'}, '2019-04-05': {'1. open': '1184.1000', '2. high': '1216.3000', '3. low': '1182.0000', '4. close': '1207.1500', '5. volume': '4956467'}, '2019-03-29': {'1. open': '1196.9300', '2. high': '1206.4000', '3. low': '1159.3700', '4. close': '1173.3100', '5. volume': '7080648'}, '2019-03-22': {'1. open': '1183.3000', '2. high': '1231.7900', '3. low': '1177.4200', '4. close': '1205.5000', '5. volume': '7959399'}, '2019-03-15': {'1. open': '1144.4500', '2. high': '1200.9300', '3. low': '1144.4500', '4. close': '1184.4600', '5. volume': '8801015'}, '2019-03-08': {'1. open': '1146.9900', '2. high': '1169.6100', '3. low': '1123.3000', '4. close': '1142.3200', '5. volume': '6367558'}, '2019-03-01': {'1. open': '1116.0000', '2. high': '1142.9700', '3. low': '1099.9200', '4. close': '1140.9900', '5. volume': '6846489'}, '2019-02-22': {'1. open': '1110.0000', '2. high': '1123.4100', '3. low': '1092.5200', '4. close': '1110.3700', '5. volume': '4599463'}, '2019-02-15': {'1. open': '1096.9500', '2. high': '1134.7300', '3. low': '1092.8600', '4. close': '1113.6500', '5. volume': '6121950'}, '2019-02-08': {'1. open': '1112.6600', '2. high': '1147.0000', '3. low': '1086.0000', '4. close': '1095.0600', '5. volume': '11354852'}, '2019-02-01': {'1. open': '1080.1100', '2. high': '1125.0000', '3. low': '1055.8600', '4. close': '1110.7500', '5. volume': '6586454'}, '2019-01-25': {'1. open': '1088.0000', '2. high': '1094.0000', '3. low': '1059.7500', '4. close': '1090.9900', '5. volume': '5061372'}, '2019-01-18': {'1. open': '1046.9200', '2. high': '1108.3500', '3. low': '1041.2600', '4. close': '1098.2600', '5. volume': '7137875'}, '2019-01-11': {'1. open': '1071.5000', '2. high': '1084.5600', '3. low': '1048.4800', '4. close': '1057.1900', '5. volume': '7923590'}, '2019-01-04': {'1. open': '1050.9600', '2. high': '1070.8400', '3. low': '1014.0700', '4. close': '1070.7100', '5. volume': '6961290'}, '2018-12-28': {'1. open': '973.9000', '2. high': '1055.5600', '

In [3]:
google_weekly_df = pd.DataFrame.from_dict(google_weekly_data['Weekly Time Series']).T
google_weekly_df.head(50)

              1. open    2. high     3. low   4. close 5. volume
2021-10-08  2713.9900  2806.3400  2623.3300  2801.1200   5629992
2021-10-01  2831.7100  2850.0000  2660.0000  2729.2500   7556112
2021-09-24  2780.0035  2858.0700  2741.0600  2852.6600   5367017
2021-09-17  2864.0200  2911.6300  2821.2300  2829.2700   7004342
2021-09-10  2894.9900  2920.3800  2834.8300  2838.4200   3917972
2021-09-03  2894.0900  2936.4099  2870.1000  2895.5000   5023164
2021-08-27  2779.9700  2900.2200  2774.9586  2891.0100   4427462
2021-08-20  2760.0000  2779.8100  2707.1200  2768.7400   4406099
2021-08-13  2738.9800  2776.9550  2728.5750  2768.1200   3540233
2021-08-06  2709.6900  2741.6009  2683.6700  2740.7200   4058399
2021-07-30  2765.0000  2800.2200  2696.2840  2704.4200   8141483
2021-07-23  2623.1100  2776.1700  2570.7400  2756.3200   4975998
2021-07-16  2596.6700  2659.9199  2592.0000  2636.9100   4146746
2021-07-09  2588.9900  2612.7983  2560.8000  2591.4900   3646144
2021-07-02  2540.0000  2576.9600  2495.1500  2574.3800   5567985
2021-06-25  2514.8000  2555.9200  2502.6850  2539.9000   5967753
2021-06-18  2513.3900  2543.9300  2482.9994  2511.3500   7496921
2021-06-11  2451.3200  2526.9900  2441.0725  2513.9300   6276085
2021-06-04  2422.0000  2453.8590  2382.8300  2451.7600   4031119
2021-05-28  2367.0000  2442.9440  2360.1100  2411.5600   6250431
2021-05-21  2309.3200  2368.9999  2263.5200  2345.1000   5158304
2021-05-14  2374.8900  2378.0000  2230.0500  2316.1600   7317239
2021-05-07  2402.7200  2419.7000  2311.7000  2398.6900   6730430
2021-04-30  2319.9300  2452.3780  2304.2700  2410.1200   9561479
2021-04-23  2291.9800  2325.8200  2256.4500  2315.3000   6009895
2021-04-16  2266.2500  2306.5965  2238.4650  2297.7600   6246324
2021-04-09  2152.9400  2289.0400  2151.6200  2285.8800   7210396
2021-04-01  2027.8800  2142.9400  2015.6200  2137.7500   5425459
2021-03-26  2041.8400  2078.2100  2010.7300  2035.5500   7388549
2021-03-19  2062.3000  2123.5600  2017.6800  2043.2000   7766228
2021-03-12  2101.1300  2128.8100  2021.6100  2061.9200   7578201
2021-03-05  2056.5200  2118.1100  2010.0000  2108.5400   8337115
2021-02-26  2067.0000  2100.7800  2002.0200  2036.8600   8103757
2021-02-19  2104.3600  2152.6800  2097.4100  2101.1400   4733557
2021-02-12  2105.9100  2123.5469  2063.0900  2104.1100   5062914
2021-02-05  1853.5700  2116.5000  1850.9300  2098.0000  11211680
2021-01-29  1920.6700  1929.5800  1809.0000  1835.7400   9374441
2021-01-22  1752.2500  1934.8600  1741.4600  1901.0500   7561036
2021-01-15  1786.0700  1794.3150  1721.5500  1736.1900   6181977
2021-01-08  1757.5400  1809.8400  1699.0000  1807.2100   9965340
2020-12-31  1751.6350  1792.4400  1725.6000  1751.8800   5008727
2020-12-24  1713.5100  1747.9900  1699.0000  1738.8500   4147394
2020-12-18  1775.0000  1797.3900  1720.2200  1731.0100  10237074
2020-12-11  1819.0000  1834.2700  1740.3200  1781.7700   6508322
2020-12-04  1781.1844  1847.2000  1755.0000  1827.9900   7344925
2020-11-27  1749.6000  1804.0000  1717.7200  1793.1900   5584711
2020-11-20  1771.7000  1799.0700  1737.0050  1742.1900   7130930
2020-11-13  1790.9000  1818.0600  1717.3000  1777.0200   8917706
2020-11-06  1628.1600  1793.6400  1616.0300  1761.7500  11495063
2020-10-30  1625.0100  1687.0000  1514.6200  1621.0100  11250141

In [5]:
url = 'https://www.alphavantage.co/query?function=MACD&symbol=GOOG&interval=weekly&series_type=open&apikey=PLWHFCZSI5GFFUMN'
r = requests.get(url)
google_macd_weekly = r.json()

print(google_macd_weekly)

{'Meta Data': {'1: Symbol': 'GOOG', '2: Indicator': 'Moving Average Convergence/Divergence (MACD)', '3: Last Refreshed': '2021-10-08', '4: Interval': 'weekly', '5.1: Fast Period': 12, '5.2: Slow Period': 26, '5.3: Signal Period': 9, '6: Series Type': 'open', '7: Time Zone': 'US/Eastern'}, 'Technical Analysis: MACD': {'2021-10-08': {'MACD_Hist': '-20.1510', 'MACD_Signal': '187.9052', 'MACD': '167.7542'}, '2021-10-01': {'MACD_Hist': '-8.4470', 'MACD_Signal': '192.9430', 'MACD': '184.4960'}, '2021-09-24': {'MACD_Hist': '-3.8598', 'MACD_Signal': '195.0547', 'MACD': '191.1950'}, '2021-09-17': {'MACD_Hist': '6.2093', 'MACD_Signal': '196.0197', 'MACD': '202.2290'}, '2021-09-10': {'MACD_Hist': '10.3490', 'MACD_Signal': '194.4674', 'MACD': '204.8164'}, '2021-09-03': {'MACD_Hist': '10.1064', 'MACD_Signal': '191.8801', 'MACD': '201.9865'}, '2021-08-27': {'MACD_Hist': '6.1746', 'MACD_Signal': '189.3535', 'MACD': '195.5282'}, '2021-08-20': {'MACD_Hist': '8.2506', 'MACD_Signal': '187.8099', 'MACD': '196.0604'}, '2021-08-13': {'MACD_Hist': '10.1741', 'MACD_Signal': '185.7472', 'MACD': '195.9213'}, '2021-08-06': {'MACD_Hist': '11.8305', 'MACD_Signal': '183.2037', 'MACD': '195.0342'}, '2021-07-30': {'MACD_Hist': '13.8012', 'MACD_Signal': '180.2461', 'MACD': '194.0473'}, '2021-07-23': {'MACD_Hist': '7.5377', 'MACD_Signal': '176.7958', 'MACD': '184.3335'}, '2021-07-16': {'MACD_Hist': '8.7897', 'MACD_Signal': '174.9114', 'MACD': '183.7011'}, '2021-07-09': {'MACD_Hist': '10.1999', 'MACD_Signal': '172.7139', 'MACD': '182.9139'}, '2021-07-02': {'MACD_Hist': '9.8666', 'MACD_Signal': '170.1639', 'MACD': '180.0305'}, '2021-06-25': {'MACD_Hist': '11.0224', 'MACD_Signal': '167.6973', 'MACD': '178.7197'}, '2021-06-18': {'MACD_Hist': '12.0713', 'MACD_Signal': '164.9417', 'MACD': '177.0130'}, '2021-06-11': {'MACD_Hist': '10.4795', 'MACD_Signal': '161.9239', 'MACD': '172.4034'}, '2021-06-04': {'MACD_Hist': '11.0280', 'MACD_Signal': '159.3040', 'MACD': '170.3320'}, '2021-05-28': {'MACD_Hist': '11.6489', 'MACD_Signal': '156.5470', 'MACD': '168.1959'}, '2021-05-21': {'MACD_Hist': '14.9882', 'MACD_Signal': '153.6348', 'MACD': '168.6230'}, '2021-05-14': {'MACD_Hist': '22.7005', 'MACD_Signal': '149.8878', 'MACD': '172.5883'}, '2021-05-07': {'MACD_Hist': '24.2502', 'MACD_Signal': '144.2126', 'MACD': '168.4629'}, '2021-04-30': {'MACD_Hist': '19.7633', 'MACD_Signal': '138.1501', 'MACD': '157.9134'}, '2021-04-23': {'MACD_Hist': '17.3717', 'MACD_Signal': '133.2093', 'MACD': '150.5810'}, '2021-04-16': {'MACD_Hist': '13.0114', 'MACD_Signal': '128.8663', 'MACD': '141.8777'}, '2021-04-09': {'MACD_Hist': '5.7118', 'MACD_Signal': '125.6135', 'MACD': '131.3253'}, '2021-04-01': {'MACD_Hist': '3.2979', 'MACD_Signal': '124.1855', 'MACD': '127.4834'}, '2021-03-26': {'MACD_Hist': '10.0978', 'MACD_Signal': '123.3611', 'MACD': '133.4588'}, '2021-03-19': {'MACD_Hist': '16.8864', 'MACD_Signal': '120.8366', 'MACD': '137.7231'}, '2021-03-12': {'MACD_Hist': '22.4643', 'MACD_Signal': '116.6150', 'MACD': '139.0793'}, '2021-03-05': {'MACD_Hist': '23.8348', 'MACD_Signal': '110.9990', 'MACD': '134.8338'}, '2021-02-26': {'MACD_Hist': '26.9556', 'MACD_Signal': '105.0403', 'MACD': '131.9959'}, '2021-02-19': {'MACD_Hist': '27.0853', 'MACD_Signal': '98.3014', 'MACD': '125.3867'}, '2021-02-12': {'MACD_Hist': '19.7932', 'MACD_Signal': '91.5300', 'MACD': '111.3232'}, '2021-02-05': {'MACD_Hist': '5.0143', 'MACD_Signal': '86.5817', 'MACD': '91.5960'}, '2021-01-29': {'MACD_Hist': '5.4493', 'MACD_Signal': '85.3281', 'MACD': '90.7775'}, '2021-01-22': {'MACD_Hist': '-2.3855', 'MACD_Signal': '83.9658', 'MACD': '81.5803'}, '2021-01-15': {'MACD_Hist': '1.2407', 'MACD_Signal': '84.5622', 'MACD': '85.8029'}, '2021-01-08': {'MACD_Hist': '2.2490', 'MACD_Signal': '84.2520', 'MACD': '86.5010'}, '2020-12-31': {'MACD_Hist': '5.3490', 'MACD_Signal': '83.6897', 'MACD': '89.0387'}, '2020-12-24': {'MACD_Hist': '9.2314', 'MACD_Signal': '82.3525', 'MACD': '91.5839'}, '2020-12-18': {'MACD_Hist': '17.3375', 'MACD_Signal': '80.0446', 'MACD': '97.3821'}, '2020-12-11': {'MACD_Hist': '21.3953', 'MACD_Signal': '75.7103', 'MACD': '97.1055'}, '2020-12-04': {'MACD_Hist': '20.4986', 'MACD_Signal': '70.3615', 'MACD': '90.8600'}, '2020-11-27': {'MACD_Hist': '20.1804', 'MACD_Signal': '65.2368', 'MACD': '85.4172'}, '2020-11-20': {'MACD_Hist': '20.2520', 'MACD_Signal': '60.1917', 'MACD': '80.4437'}, '2020-11-13': {'MACD_Hist': '15.5466', 'MACD_Signal': '55.1287', 'MACD': '70.6753'}, '2020-11-06': {'MACD_Hist': '3.9824', 'MACD_Signal': '51.2420', 'MACD': '55.2245'}, '2020-10-30': {'MACD_Hist': '1.0237', 'MACD_Signal': '50.2464', 'MACD': '51.2702'}, '2020-10-23': {'MACD_Hist': '-4.1925', 'MACD_Signal': '49.9905', 'MACD': '45.7980'}, '2020-10-16': {'MACD_Hist': '-8.3552', 'MACD_Signal': '51.0386', 'MACD': '42.6834'}, '2020-10-09': {'MACD_Hist': '-11.2261', 'MACD_Signal': '53.1274', 'MACD': '41.9013'}, '2020-10-02': {'MACD_Hist': '-7.8218', 'MACD_Signal': '55.9339', 'MACD': '48.1122'}, '2020-09-25': {'MACD_Hist': '-3.3642', 'MACD_Signal': '57.8894', 'MACD': '54.5252'}, '2020-09-18': {'MACD_Hist': '6.6640', 'MACD_Signal': '58.7305', 'MACD': '65.3945'}, '2020-09-11': {'MACD_Hist': '11.1776', 'MACD_Signal': '57.0645', 'MACD': '68.2420'}, '2020-09-04': {'MACD_Hist': '17.1734', 'MACD_Signal': '54.2701', 'MACD': '71.4435'}, '2020-08-28': {'MACD_Hist': '12.8678', 'MACD_Signal': '49.9767', 'MACD': '62.8445'}, '2020-08-21': {'MACD_Hist': '9.6843', 'MACD_Signal': '46.7597', 'MACD': '56.4441'}, '2020-08-14': {'MACD_Hist': '11.1903', 'MACD_Signal': '44.3387', 'MACD': '55.5289'}, '2020-08-07': {'MACD_Hist': '14.8111', 'MACD_Signal': '41.5411', 'MACD': '56.3522'}, '2020-07-31': {'MACD_Hist': '18.7999', 'MACD_Signal': '37.8383', 'MACD': '56.6383'}, '2020-07-24': {'MACD_Hist': '20.0926', 'MACD_Signal': '33.1384', 'MACD': '53.2309'}, '2020-07-17': {'MACD_Hist': '20.0270', 'MACD_Signal': '28.1152', 'MACD': '48.1423'}, '2020-07-10': {'MACD_Hist': '14.3014', 'MACD_Signal': '23.1085', 'MACD': '37.4099'}, '2020-07-02': {'MACD_Hist': '10.7553', 'MACD_Signal': '19.5331', 'MACD': '30.2884'}, '2020-06-26': {'MACD_Hist': '16.3237', 'MACD_Signal': '16.8443', 'MACD': '33.1680'}, '2020-06-19': {'MACD_Hist': '16.3867', 'MACD_Signal': '12.7633', 'MACD': '29.1501'}, '2020-06-12': {'MACD_Hist': '18.8206', 'MACD_Signal': '8.6667', 'MACD': '27.4873'}, '2020-06-05': {'MACD_Hist': '17.7922', 'MACD_Signal': '3.9615', 'MACD': '21.7537'}, '2020-05-29': {'MACD_Hist': '15.0080', 'MACD_Signal': '-0.4865', 'MACD': '14.5214'}, '2020-05-22': {'MACD_Hist': '7.3954', 'MACD_Signal': '-4.2385', 'MACD': '3.1568'}, '2020-05-15': {'MACD_Hist': '2.3822', 'MACD_Signal': '-6.0874', 'MACD': '-3.7052'}, '2020-05-08': {'MACD_Hist': '-7.4098', 'MACD_Signal': '-6.6829', 'MACD': '-14.0927'}, '2020-05-01': {'MACD_Hist': '-15.1831', 'MACD_Signal': '-4.8305', 'MACD': '-20.0136'}, '2020-04-24': {'MACD_Hist': '-24.9998', 'MACD_Signal': '-1.0347', 'MACD': '-26.0345'}, '2020-04-17': {'MACD_Hist': '-36.0105', 'MACD_Signal': '5.2152', 'MACD': '-30.7953'}, '2020-04-09': {'MACD_Hist': '-44.3472', 'MACD_Signal': '14.2179', 'MACD': '-30.1294'}, '2020-04-03': {'MACD_Hist': '-46.8984', 'MACD_Signal': '25.3047', 'MACD': '-21.5938'}, '2020-03-27': {'MACD_Hist': '-46.0948', 'MACD_Signal': '37.0293', 'MACD': '-9.0656'}, '2020-03-20': {'MACD_Hist': '-35.0083', 'MACD_Signal': '48.5530', 'MACD': '13.5447'}, '2020-03-13': {'MACD_Hist': '-18.6296', 'MACD_Signal': '57.3051', 'MACD': '38.6755'}, '2020-03-06': {'MACD_Hist': '-2.9022', 'MACD_Signal': '61.9625', 'MACD': '59.0602'}, '2020-02-28': {'MACD_Hist': '6.6345', 'MACD_Signal': '62.6880', 'MACD': '69.3226'}, '2020-02-21': {'MACD_Hist': '12.7978', 'MACD_Signal': '61.0294', 'MACD': '73.8272'}, '2020-02-14': {'MACD_Hist': '11.6224', 'MACD_Signal': '57.8299', 'MACD': '69.4523'}, '2020-02-07': {'MACD_Hist': '12.0758', 'MACD_Signal': '54.9243', 'MACD': '67.0001'}, '2020-01-31': {'MACD_Hist': '12.2447', 'MACD_Signal': '51.9054', 'MACD': '64.1501'}, '2020-01-24': {'MACD_Hist': '13.8915', 'MACD_Signal': '48.8442', 'MACD': '62.7356'}, '2020-01-17': {'MACD_Hist': '9.7470', 'MACD_Signal': '45.3713', 'MACD': '55.1183'}, '2020-01-10': {'MACD_Hist': '6.0367', 'MACD_Signal': '42.9346', 'MACD': '48.9713'}, '2020-01-03': {'MACD_Hist': '7.7573', 'MACD_Signal': '41.4254', 'MACD': '49.1827'}, '2019-12-27': {'MACD_Hist': '9.2511', 'MACD_Signal': '39.4861', 'MACD': '48.7372'}, '2019-12-20': {'MACD_Hist': '9.6887', 'MACD_Signal': '37.1733', 'MACD': '46.8620'}, '2019-12-13': {'MACD_Hist': '8.9716', 'MACD_Signal': '34.7511', 'MACD': '43.7227'}, '2019-12-06': {'MACD_Hist': '8.4513', 'MACD_Signal': '32.5082', 'MACD': '40.9595'}, '2019-11-29': {'MACD_Hist': '10.2128', 'MACD_Signal': '30.3954', 'MACD': '40.6082'}, '2019-11-22': {'MACD_Hist': '11.9122', 'MACD_Signal': '27.8422', 'MACD': '39.7545'}, '2019-11-15': {'MACD_Hist': '9.8583', 'MACD_Signal': '24.8642', 'MACD': '34.7225'}, '2019-11-08': {'MACD_Hist': '8.3520', 'MACD_Signal': '22.3996', 'MACD': '30.7516'}, '2019-11-01': {'MACD_Hist': '7.6459', 'MACD_Signal': '20.3116', 'MACD': '27.9575'}, '2019-10-25': {'MACD_Hist': '5.6864', 'MACD_Signal': '18.4001', 'MACD': '24.0865'}, '2019-10-18': {'MACD_Hist': '4.1779', 'MACD_Signal': '16.9785', 'MACD': '21.1565'}, '2019-10-11': {'MACD_Hist': '5.2395', 'MACD_Signal': '15.9340', 'MACD': '21.1735'}, '2019-10-04': {'MACD_Hist': '7.0716', 'MACD_Signal': '14.6242', 'MACD': '21.6958'}, '2019-09-27': {'MACD_Hist': '7.5034', 'MACD_Signal': '12.8563', 'MACD': '20.3596'}, '2019-09-20': {'MACD_Hist': '6.8655', 'MACD_Signal': '10.9804', 'MACD': '17.8460'}, '2019-09-13': {'MACD_Hist': '4.7556', 'MACD_Signal': '9.2641', 'MACD': '14.0196'}, '2019-09-06': {'MACD_Hist': '3.4551', 'MACD_Signal': '8.0752', 'MACD': '11.5303'}, '2019-08-30': {'MACD_Hist': '3.7199', 'MACD_Signal': '7.2114', 'MACD': '10.9313'}, '2019-08-23': {'MACD_Hist': '5.7393', 'MACD_Signal': '6.2814', 'MACD': '12.0207'}, '2019-08-16': {'MACD_Hist': '5.0472', 'MACD_Signal': '4.8466', 'MACD': '9.8937'}, '2019-08-09': {'MACD_Hist': '4.5580', 'MACD_Signal': '3.5848', 'MACD': '8.1428'}, '2019-08-02': {'MACD_Hist': '4.2778', 'MACD_Signal': '2.4453', 'MACD': '6.7231'}, '2019-07-26': {'MACD_Hist': '-3.7926', 'MACD_Signal': '1.3758', 'MACD': '-2.4168'}, '2019-07-19': {'MACD_Hist': '-5.4158', 'MACD_Signal': '2.3240', 'MACD': '-3.0918'}, '2019-07-12': {'MACD_Hist': '-8.9517', 'MACD_Signal': '3.6779', 'MACD': '-5.2738'}, '2019-07-05': {'MACD_Hist': '-11.6895', 'MACD_Signal': '5.9159', 'MACD': '-5.7737'}, '2019-06-28': {'MACD_Hist': '-12.3996', 'MACD_Signal': '8.8383', 'MACD': '-3.5613'}, '2019-06-21': {'MACD_Hist': '-14.8241', 'MACD_Signal': '11.9381', 'MACD': '-2.8860'}, '2019-06-14': {'MACD_Hist': '-14.2327', 'MACD_Signal': '15.6442', 'MACD': '1.4115'}, '2019-06-07': {'MACD_Hist': '-10.9720', 'MACD_Signal': '19.2023', 'MACD': '8.2303'}, '2019-05-31': {'MACD_Hist': '-4.3699', 'MACD_Signal': '21.9454', 'MACD': '17.5755'}, '2019-05-24': {'MACD_Hist': '-0.7647', 'MACD_Signal': '23.0378', 'MACD': '22.2732'}, '2019-05-17': {'MACD_Hist': '3.6471', 'MACD_Signal': '23.2290', 'MACD': '26.8760'}, '2019-05-10': {'MACD_Hist': '10.3014', 'MACD_Signal': '22.3172', 'MACD': '32.6187'}, '2019-05-03': {'MACD_Hist': '17.2578', 'MACD_Signal': '19.7419', 'MACD': '36.9997'}, '2019-04-26': {'MACD_Hist': '15.6560', 'MACD_Signal': '15.4274', 'MACD': '31.0834'}, '2019-04-18': {'MACD_Hist': '15.4367', 'MACD_Signal': '11.5134', 'MACD': '26.9501'}, '2019-04-12': {'MACD_Hist': '15.4600', 'MACD_Signal': '7.6542', 'MACD': '23.1142'}, '2019-04-05': {'MACD_Hist': '15.1221', 'MACD_Signal': '3.7892', 'MACD': '18.9113'}, '2019-03-29': {'MACD_Hist': '15.6855', 'MACD_Signal': '0.0087', 'MACD': '15.6942'}, '2019-03-22': {'MACD_Hist': '13.9660', 'MACD_Signal': '-3.9127', 'MACD': '10.0533'}, '2019-03-15': {'MACD_Hist': '11.4992', 'MACD_Signal': '-7.4042', 'MACD': '4.0950'}, '2019-03-08': {'MACD_Hist': '10.6651', 'MACD_Signal': '-10.2790', 'MACD': '0.3861'}, '2019-03-01': {'MACD_Hist': '8.3333', 'MACD_Signal': '-12.9453', 'MACD': '-4.6120'}, '2019-02-22': {'MACD_Hist': '7.2597', 'MACD_Signal': '-15.0286', 'MACD': '-7.7689'}, '2019-02-15': {'MACD_Hist': '5.7691', 'MACD_Signal': '-16.8435', 'MACD': '-11.0744'}, '2019-02-08': {'MACD_Hist': '4.4821', 'MACD_Signal': '-18.2858', 'MACD': '-13.8036'}, '2019-02-01': {'MACD_Hist': '0.7204', 'MACD_Signal': '-19.4063', 'MACD': '-18.6859'}, '2019-01-25': {'MACD_Hist': '-1.7451', 'MACD_Signal': '-19.5864', 'MACD': '-21.3315'}, '2019-01-18': {'MACD_Hist': '-6.0511', 'MACD_Signal': '-19.1501', 'MACD': '-25.2012'}, '2019-01-11': {'MACD_Hist': '-7.9539', 'MACD_Signal': '-17.6373', 'MACD': '-25.5912'}, '2019-01-04': {'MACD_Hist': '-12.5706', 'MACD_Signal': '-15.6488', 'MACD': '-28.2194'}, '2018-12-28': {'MACD_Hist': '-16.5660', 'MACD_Signal': '-12.5062', 'MACD': '-29.0722'}, '2018-12-21': {'MACD_Hist': '-13.5269', 'MACD_Signal': '-8.3647', 'MACD': '-21.8916'}, '2018-12-14': {'MACD_Hist': '-13.9019', 'MACD_Signal': '-4.9830', 'MACD': '-18.8849'}, '2018-12-07': {'MACD_Hist': '-13.0145', 'MACD_Signal': '-1.5075', 'MACD': '-14.5220'}, '2018-11-30': {'MACD_Hist': '-19.4574', 'MACD_Signal': '1.7461', 'MACD': '-17.7112'}, '2018-11-23': {'MACD_Hist': '-19.5016', 'MACD_Signal': '6.6105', 'MACD': '-12.8912'}, '2018-11-16': {'MACD_Hist': '-19.9566', 'MACD_Signal': '11.4859', 'MACD': '-8.4707'}, '2018-11-09': {'MACD_Hist': '-19.6071', 'MACD_Signal': '16.4750', 'MACD': '-3.1321'}, '2018-11-02': {'MACD_Hist': '-16.9986', 'MACD_Signal': '21.3768', 'MACD': '4.3782'}, '2018-10-26': {'MACD_Hist': '-14.5231', 'MACD_Signal': '25.6265', 'MACD': '11.1033'}, '2018-10-19': {'MACD_Hist': '-11.8281', 'MACD_Signal': '29.2573', 'MACD': '17.4292'}, '2018-10-12': {'MACD_Hist': '-7.5602', 'MACD_Signal': '32.2143', 'MACD': '24.6541'}, '2018-10-05': {'MACD_Hist': '-4.7821', 'MACD_Signal': '34.1043', 'MACD': '29.3222'}, '2018-09-28': {'MACD_Hist': '-5.5145', 'MACD_Signal': '35.2999', 'MACD': '29.7854'}, '2018-09-21': {'MACD_Hist': '-2.3855', 'MACD_Signal': '36.6785', 'MACD': '34.2930'}, '2018-09-14': {'MACD_Hist': '0.9521', 'MACD_Signal': '37.2749', 'MACD': '38.2269'}, '2018-09-07': {'MACD_Hist': '5.4465', 'MACD_Signal': '37.0369', 'MACD': '42.4834'}, '2018-08-31': {'MACD_Hist': '8.3566', 'MACD_Signal': '35.6752', 'MACD': '44.0318'}, '2018-08-24': {'MACD_Hist': '9.4063', 'MACD_Signal': '33.5861', 'MACD': '42.9924'}, '2018-08-17': {'MACD_Hist': '12.1048', 'MACD_Signal': '31.2345', 'MACD': '43.3393'}, '2018-08-10': {'MACD_Hist': '11.6894', 'MACD_Signal': '28.2083', 'MACD': '39.8977'}, '2018-08-03': {'MACD_Hist': '10.8584', 'MACD_Signal': '25.2860', 'MACD': '36.1443'}, '2018-07-27': {'MACD_Hist': '7.9501', 'MACD_Signal': '22.5714', 'MACD': '30.5215'}, '2018-07-20': {'MACD_Hist': '7.1024', 'MACD_Signal': '20.5838', 'MACD': '27.6862'}, '2018-07-13': {'MACD_Hist': '4.0032', 'MACD_Signal': '18.8082', 'MACD': '22.8114'}, '2018-07-06': {'MACD_Hist': '2.6156', 'MACD_Signal': '17.8074', 'MACD': '20.4230'}, '2018-06-29': {'MACD_Hist': '4.9619', 'MACD_Signal': '17.1535', 'MACD': '22.1154'}, '2018-06-22': {'MACD_Hist': '3.4997', 'MACD_Signal': '15.9131', 'MACD': '19.4127'}, '2018-06-15': {'MACD_Hist': '0.6376', 'MACD_Signal': '15.0382', 'MACD': '15.6757'}, '2018-06-08': {'MACD_Hist': '-1.6503', 'MACD_Signal': '14.8788', 'MACD': '13.2285'}, '2018-06-01': {'MACD_Hist': '-5.7587', 'MACD_Signal': '15.2913', 'MACD': '9.5327'}, '2018-05-25': {'MACD_Hist': '-6.2058', 'MACD_Signal': '16.7310', 'MACD': '10.5253'}, '2018-05-18': {'MACD_Hist': '-7.5770', 'MACD_Signal': '18.2825', 'MACD': '10.7054'}, '2018-05-11': {'MACD_Hist': '-12.0382', 'MACD_Signal': '20.1767', 'MACD': '8.1385'}, '2018-05-04': {'MACD_Hist': '-13.2732', 'MACD_Signal': '23.1863', 'MACD': '9.9131'}, '2018-04-27': {'MACD_Hist': '-12.5138', 'MACD_Signal': '26.5046', 'MACD': '13.9908'}, '2018-04-20': {'MACD_Hist': '-15.5130', 'MACD_Signal': '29.6330', 'MACD': '14.1200'}, '2018-04-13': {'MACD_Hist': '-15.2714', 'MACD_Signal': '33.5113', 'MACD': '18.2399'}, '2018-04-06': {'MACD_Hist': '-12.0395', 'MACD_Signal': '37.3291', 'MACD': '25.2897'}, '2018-03-29': {'MACD_Hist': '-7.0320', 'MACD_Signal': '40.3390', 'MACD': '33.3070'}, '2018-03-23': {'MACD_Hist': '-1.4016', 'MACD_Signal': '42.0970', 'MACD': '40.6954'}, '2018-03-16': {'MACD_Hist': '-0.4491', 'MACD_Signal': '42.4474', 'MACD': '41.9983'}, '2018-03-09': {'MACD_Hist': '-3.9731', 'MACD_Signal': '42.5597', 'MACD': '38.5865'}, '2018-03-02': {'MACD_Hist': '-0.8500', 'MACD_Signal': '43.5529', 'MACD': '42.7030'}, '2018-02-23': {'MACD_Hist': '-1.7913', 'MACD_Signal': '43.7654', 'MACD': '41.9742'}, '2018-02-16': {'MACD_Hist': '0.0108', 'MACD_Signal': '44.2133', 'MACD': '44.2241'}, '2018-02-09': {'MACD_Hist': '6.5764', 'MACD_Signal': '44.2106', 'MACD': '50.7870'}, '2018-02-02': {'MACD_Hist': '11.5209', 'MACD_Signal': '42.5665', 'MACD': '54.0874'}, '2018-01-26': {'MACD_Hist': '9.0828', 'MACD_Signal': '39.6862', 'MACD': '48.7691'}, '2018-01-19': {'MACD_Hist': '7.8259', 'MACD_Signal': '37.4155', 'MACD': '45.2415'}, '2018-01-12': {'MACD_Hist': '5.1290', 'MACD_Signal': '35.4590', 'MACD': '40.5880'}, '2018-01-05': {'MACD_Hist': '2.9643', 'MACD_Signal': '34.1768', 'MACD': '37.1411'}, '2017-12-29': {'MACD_Hist': '4.2527', 'MACD_Signal': '33.4357', 'MACD': '37.6884'}, '2017-12-22': {'MACD_Hist': '4.4756', 'MACD_Signal': '32.3725', 'MACD': '36.8481'}, '2017-12-15': {'MACD_Hist': '3.1704', 'MACD_Signal': '31.2537', 'MACD': '34.4240'}, '2017-12-08': {'MACD_Hist': '3.4818', 'MACD_Signal': '30.4611', 'MACD': '33.9429'}, '2017-12-01': {'MACD_Hist': '5.5700', 'MACD_Signal': '29.5906', 'MACD': '35.1606'}, '2017-11-24': {'MACD_Hist': '5.2215', 'MACD_Signal': '28.1981', 'MACD': '33.4197'}, '2017-11-17': {'MACD_Hist': '5.8287', 'MACD_Signal': '26.8927', 'MACD': '32.7214'}, '2017-11-10': {'MACD_Hist': '5.5969', 'MACD_Signal': '25.4356', 'MACD': '31.0325'}, '2017-11-03': {'MACD_Hist': '3.8220', 'MACD_Signal': '24.0363', 'MACD': '27.8583'}, '2017-10-27': {'MACD_Hist': '1.8471', 'MACD_Signal': '23.0808', 'MACD': '24.9280'}, '2017-10-20': {'MACD_Hist': '0.6986', 'MACD_Signal': '22.6191', 'MACD': '23.3177'}, '2017-10-13': {'MACD_Hist': '-1.7839', 'MACD_Signal': '22.4444', 'MACD': '20.6605'}, '2017-10-06': {'MACD_Hist': '-4.6899', 'MACD_Signal': '22.8904', 'MACD': '18.2005'}, '2017-09-29': {'MACD_Hist': '-7.2286', 'MACD_Signal': '24.0629', 'MACD': '16.8342'}, '2017-09-22': {'MACD_Hist': '-7.5087', 'MACD_Signal': '25.8700', 'MACD': '18.3614'}, '2017-09-15': {'MACD_Hist': '-7.1498', 'MACD_Signal': '27.7472', 'MACD': '20.5973'}, '2017-09-08': {'MACD_Hist': '-7.8329', 'MACD_Signal': '29.5347', 'MACD': '21.7018'}, '2017-09-01': {'MACD_Hist': '-8.5780', 'MACD_Signal': '31.4929', 'MACD': '22.9149'}, '2017-08-25': {'MACD_Hist': '-7.7683', 'MACD_Signal': '33.6374', 'MACD': '25.8690'}, '2017-08-18': {'MACD_Hist': '-5.7052', 'MACD_Signal': '35.5795', 'MACD': '29.8742'}, '2017-08-11': {'MACD_Hist': '-3.7298', 'MACD_Signal': '37.0058', 'MACD': '33.2760'}, '2017-08-04': {'MACD_Hist': '-1.4692', 'MACD_Signal': '37.9382', 'MACD': '36.4690'}, '2017-07-28': {'MACD_Hist': '0.4021', 'MACD_Signal': '38.3055', 'MACD': '38.7076'}, '2017-07-21': {'MACD_Hist': '-0.2913', 'MACD_Signal': '38.2050', 'MACD': '37.9137'}, '2017-07-14': {'MACD_Hist': '-0.3792', 'MACD_Signal': '38.2778', 'MACD': '37.8987'}, '2017-07-07': {'MACD_Hist': '2.5426', 'MACD_Signal': '38.3726', 'MACD': '40.9152'}, '2017-06-30': {'MACD_Hist': '7.4099', 'MACD_Signal': '37.7369', 'MACD': '45.1468'}, '2017-06-23': {'MACD_Hist': '8.1297', 'MACD_Signal': '35.8845', 'MACD': '44.0142'}, '2017-06-16': {'MACD_Hist': '10.1066', 'MACD_Signal': '33.8520', 'MACD': '43.9586'}, '2017-06-09': {'MACD_Hist': '12.9818', 'MACD_Signal': '31.3254', 'MACD': '44.3072'}, '2017-06-02': {'MACD_Hist': '12.2614', 'MACD_Signal': '28.0800', 'MACD': '40.3413'}, '2017-05-26': {'MACD_Hist': '10.3134', 'MACD_Signal': '25.0146', 'MACD': '35.3281'}, '2017-05-19': {'MACD_Hist': '9.5744', 'MACD_Signal': '22.4363', 'MACD': '32.0106'}, '2017-05-12': {'MACD_Hist': '7.4769', 'MACD_Signal': '20.0427', 'MACD': '27.5195'}, '2017-05-05': {'MACD_Hist': '3.

In [6]:
google_macd_weekly_df = pd.DataFrame.from_dict(google_macd_weekly['Technical Analysis: MACD']).T
google_macd_weekly_df.head(50)

           MACD_Hist MACD_Signal      MACD
2021-10-08  -20.1510    187.9052  167.7542
2021-10-01   -8.4470    192.9430  184.4960
2021-09-24   -3.8598    195.0547  191.1950
2021-09-17    6.2093    196.0197  202.2290
2021-09-10   10.3490    194.4674  204.8164
2021-09-03   10.1064    191.8801  201.9865
2021-08-27    6.1746    189.3535  195.5282
2021-08-20    8.2506    187.8099  196.0604
2021-08-13   10.1741    185.7472  195.9213
2021-08-06   11.8305    183.2037  195.0342
2021-07-30   13.8012    180.2461  194.0473
2021-07-23    7.5377    176.7958  184.3335
2021-07-16    8.7897    174.9114  183.7011
2021-07-09   10.1999    172.7139  182.9139
2021-07-02    9.8666    170.1639  180.0305
2021-06-25   11.0224    167.6973  178.7197
2021-06-18   12.0713    164.9417  177.0130
2021-06-11   10.4795    161.9239  172.4034
2021-06-04   11.0280    159.3040  170.3320
2021-05-28   11.6489    156.5470  168.1959
2021-05-21   14.9882    153.6348  168.6230
2021-05-14   22.7005    149.8878  172.5883
2021-05-07   24.2502    144.2126  168.4629
2021-04-30   19.7633    138.1501  157.9134
2021-04-23   17.3717    133.2093  150.5810
2021-04-16   13.0114    128.8663  141.8777
2021-04-09    5.7118    125.6135  131.3253
2021-04-01    3.2979    124.1855  127.4834
2021-03-26   10.0978    123.3611  133.4588
2021-03-19   16.8864    120.8366  137.7231
2021-03-12   22.4643    116.6150  139.0793
2021-03-05   23.8348    110.9990  134.8338
2021-02-26   26.9556    105.0403  131.9959
2021-02-19   27.0853     98.3014  125.3867
2021-02-12   19.7932     91.5300  111.3232
2021-02-05    5.0143     86.5817   91.5960
2021-01-29    5.4493     85.3281   90.7775
2021-01-22   -2.3855     83.9658   81.5803
2021-01-15    1.2407     84.5622   85.8029
2021-01-08    2.2490     84.2520   86.5010
2020-12-31    5.3490     83.6897   89.0387
2020-12-24    9.2314     82.3525   91.5839
2020-12-18   17.3375     80.0446   97.3821
2020-12-11   21.3953     75.7103   97.1055
2020-12-04   20.4986     70.3615   90.8600
2020-11-27   20.1804     65.2368   85.4172
2020-11-20   20.2520     60.1917   80.4437
2020-11-13   15.5466     55.1287   70.6753
2020-11-06    3.9824     51.2420   55.2245
2020-10-30    1.0237     50.2464   51.2702

In [8]:
google_weekly_df = google_weekly_df.reset_index()

In [9]:
google_macd_weekly_df = google_macd_weekly_df.reset_index()

In [10]:
merged_weekly_macd = pd.merge(google_weekly_df, google_macd_weekly_df , on=['index', 'index'])
merged_weekly_macd.head(50)

,index,1. open,2. high,3. low,4. close,5. volume,MACD_Hist,MACD_Signal,MACD
0,2021-10-08,2713.9900,2806.3400,2623.3300,2801.1200,5629992,-20.1510,187.9052,167.7542
1,2021-10-01,2831.7100,2850.0000,2660.0000,2729.2500,7556112,-8.4470,192.9430,184.4960
2,2021-09-24,2780.0035,2858.0700,2741.0600,2852.6600,5367017,-3.8598,195.0547,191.1950
3,2021-09-17,2864.0200,2911.6300,2821.2300,2829.2700,7004342,6.2093,196.0197,202.2290
4,2021-09-10,2894.9900,2920.3800,2834.8300,2838.4200,3917972,10.3490,194.4674,204.8164
5,2021-09-03,2894.0900,2936.4099,2870.1000,2895.5000,5023164,10.1064,191.8801,201.9865
6,2021-08-27,2779.9700,2900.2200,2774.9586,2891.0100,4427462,6.1746,189.3535,195.5282
7,2021-08-20,2760.0000,2779.8100,2707.1200,2768.7400,4406099,8.2506,187.8099,196.0604
8,2021-08-13,2738.9800,2776.9550,2728.5750,2768.1200,3540233,10.1741,185.7472,195.9213
9,2021-08-06,2709.6900,2741.6009,2683.6700,2740.7200,4058399,11.8305,183.2037,195.0342
10,2021-07-30,2765.0000,2800.2200,2696.2840,2704.4200,8141483,13.8012,180.2461,194.0473
11,2021-07-23,2623.1100,2776.1700,2570.7400,2756.3200,4975998,7.5377,176.7958,184.3335
12,2021-07-16,2596.6700,2659.9199,2592.0000,2636.9100,4146746,8.7897,174.9114,183.7011
13,2021-07-09,2588.9900,2612.7983,2560.8000,2591.4900,3646144,10.1999,172.7139,182.9139
14,2021-07-02,2540.0000,2576.9600,2495.1500,2574.3800,5567985,9.8666,170.1639,180.0305
15,2021-06-25,2514.8000,2555.9200,2502.6850,2539.9000,5967753,11.0224,167.6973,178.7197
16,2021-06-18,2513.3900,2543.9300,2482.9994,2511.3500,7496921,12.0713,164.9417,177.0130
17,2021-06-11,2451.3200,2526.9900,2441.0725,2513.9300,6276085,10.4795,161.9239,172.4034
18,2021-06-04,2422.0000,2453.8590,2382.8300,2451.7600,4031119,11.0280,159.3040,170.3320
19,2021-05-28,2367.0000,2442.9440,2360.1100,2411.5600,6250431,11.6489,156.5470,168.1959
20,2021-05-21,2309.3200,2368.9999,2263.5200,2345.1000,5158304,14.9882,153.6348,168.6230
21,2021-05-14,2374.8900,2378.0000,2230.0500,2316.1600,7317239,22.7005,149.8878,172.5883
22,2021-05-07,2402.7200,2419.7000,2311.7000,2398.6900,6730430,24.2502,144.2126,168.4629
23,2021-04-30,2319.9300,2452.3780,2304.2700,2410.1200,9561479,19.7633,138.1501,157.9134
24,2021-04-23,2291.9800,2325.8200,2256.4500,2315.3000,6009895,17.3717,133.2093,150.5810
25,2021-04-16,2266.2500,2306.5965,2238.4650,2297.7600,6246324,13.0114,128.8663,141.8777
26,2021-04-09,2152.9400,2289.0400,2151.6200,2285.8800,7210396,5.7118,125.6135,131.3253
27,2021-04-01,2027.8800,2142.9400,2015.6200,2137.7500,5425459,3.2979,124.1855,127.4834
28,2021-03-26,2041.8400,2078.2100,2010.7300,2035.5500,7388549,10.0978,123.3611,133.4588
29,2021-03-19,2062.3000,2123.5600,2017.6800,2043.2000,7766228,16.8864,120.8366,137.7231
30,2021-03-12,2101.1300,2128.8100,2021.6100,2061.9200,7578201,22.4643,116.6150,139.0793
31,2021-03-05,2056.5200,2118.1100,2010.0000,2108.5400,8337115,23.8348,110.9990,134.8338
32,2021-02-26,2067.0000,2100.7800,2002.0200,2036.8600,8103757,26.9556,105.0403,131.9959
33,2021-02-19,2104.3600,2152.6800,2097.4100,2101.1400,4733557,27.0853,98.3014,125.3867
34,2021-02-12,2105.9100,2123.5469,2063.0900,2104.1100,5062914,19.7932,91.5300,111.3232
35,2021-02-05,1853.5700,2116.5000,1850.9300,2098.0000,11211680,5.0143,86.5817,91.5960
36,2021-01-29,1920.6700,1929.5800,1809.0000,1835.7400,9374441,5.4493,85.3281,90.7775
37,2021-01-22,1752.2500,1934.8600,1741.4600,1901.0500,7561036,-2.3855,83.9658,81.5803
38,2021-01-15,1786.0700,1794.3150,1721.5500,1736.1900,6181977,1.2407,84.5622,85.8029
39,2021-01-08,1757.5400,1809.8400,1699.0000,1807.2100,9965340,2.2490,84.2520,86.5010
40,2020-12-31,1751.6350,1792.4400,1725.6000,1751.8800,5008727,5.3490,83.6897,89.0387
41,2020-12-24,1713.5100,1747.9900,1699.0000,1738.8500,4147394,9.2314,82.3525,91.5839
42,2020-12-18,1775.0000,1797.3900,1720.2200,1731.0100,10237074,17.3375,80.0446,97.3821
43,2020-12-11,1819.0000,1834.2700,1740.3200,1781.7700,6508322,21.3953,75.7103,97.1055
44,2020-12-04,1781.1844,1847.2000,1755.0000,1827.9900,7344925,20.4986,70.3615,90.8600
45,2020-11-27,1749.6000,1804.0000,1717.7200,1793.1900,5584711,20.1804,65.2368,85.4172
46,2020-11-20,1771.7000,1799.0700,1737.0050,1742.1900,7130930,20.2520,60.1917,80.4437
47,2020-11-13,1790.9000,1818.0600,1717.3000,1777.0200,8917706,15.5466,55.1287,70.6753
48,2020-11-06,1628.1600,1793.6400,1616.0300,1761.7500,11495063,3.9824,51.2420,55.2245
49,2020-10-30,1625.0100,1687.0000,1514.6200,1621.0100,11250141,1.0237,50.2464,51.2702

In [11]:
merged_weekly_macd = merged_weekly_macd.rename(columns={'index': 'Date', '1. open': 'Open', '2. high': 'High', '3. low': 'Low', '4. close': 'Close', '5. volume': 'Volume', 'MACD_Signal': 'MACD', 'MACD_Hist': 'Hist', 'MACD': 'MACD Value'})

merged_weekly_macd

,Date,Open,High,Low,Close,Volume,Hist,MACD,MACD Value
0,2021-10-08,2713.9900,2806.3400,2623.3300,2801.1200,5629992,-20.1510,187.9052,167.7542
1,2021-10-01,2831.7100,2850.0000,2660.0000,2729.2500,7556112,-8.4470,192.9430,184.4960
2,2021-09-24,2780.0035,2858.0700,2741.0600,2852.6600,5367017,-3.8598,195.0547,191.1950
3,2021-09-17,2864.0200,2911.6300,2821.2300,2829.2700,7004342,6.2093,196.0197,202.2290
4,2021-09-10,2894.9900,2920.3800,2834.8300,2838.4200,3917972,10.3490,194.4674,204.8164
...,...,...,...,...,...,...,...,...,...
355,2014-12-19,522.7400,523.1000,489.0000,516.3500,16240316,-6.9346,1.4486,-5.4859
356,2014-12-12,527.1300,536.3300,518.6600,518.6600,9515311,-7.0653,3.1823,-3.8830
357,2014-12-05,538.9000,541.4100,524.2800,525.2600,8862225,-7.1763,4.9486,-2.2277
358,2014-11-28,537.6500,543.9800,535.6200,541.8300,6151383,-8.0235,6.7427,-1.2808
359,2014-11-21,543.5800,543.7900,530.0800,537.5000,8844766,-8.6749,8.7485,0.0736

In [12]:
merged_weekly_macd.dropna()

,Date,Open,High,Low,Close,Volume,Hist,MACD,MACD Value
0,2021-10-08,2713.9900,2806.3400,2623.3300,2801.1200,5629992,-20.1510,187.9052,167.7542
1,2021-10-01,2831.7100,2850.0000,2660.0000,2729.2500,7556112,-8.4470,192.9430,184.4960
2,2021-09-24,2780.0035,2858.0700,2741.0600,2852.6600,5367017,-3.8598,195.0547,191.1950
3,2021-09-17,2864.0200,2911.6300,2821.2300,2829.2700,7004342,6.2093,196.0197,202.2290
4,2021-09-10,2894.9900,2920.3800,2834.8300,2838.4200,3917972,10.3490,194.4674,204.8164
...,...,...,...,...,...,...,...,...,...
355,2014-12-19,522.7400,523.1000,489.0000,516.3500,16240316,-6.9346,1.4486,-5.4859
356,2014-12-12,527.1300,536.3300,518.6600,518.6600,9515311,-7.0653,3.1823,-3.8830
357,2014-12-05,538.9000,541.4100,524.2800,525.2600,8862225,-7.1763,4.9486,-2.2277
358,2014-11-28,537.6500,543.9800,535.6200,541.8300,6151383,-8.0235,6.7427,-1.2808
359,2014-11-21,543.5800,543.7900,530.0800,537.5000,8844766,-8.6749,8.7485,0.0736

In [13]:
merged_weekly_macd_adjusted = merged_weekly_macd[['Date', 'Close', 'Hist']]
merged_weekly_macd_adjusted

           Date      Close      Hist
0    2021-10-08  2801.1200  -20.1510
1    2021-10-01  2729.2500   -8.4470
2    2021-09-24  2852.6600   -3.8598
3    2021-09-17  2829.2700    6.2093
4    2021-09-10  2838.4200   10.3490
..          ...        ...       ...
355  2014-12-19   516.3500   -6.9346
356  2014-12-12   518.6600   -7.0653
357  2014-12-05   525.2600   -7.1763
358  2014-11-28   541.8300   -8.0235
359  2014-11-21   537.5000   -8.6749

[360 rows x 3 columns]

In [14]:
merged_weekly_macd_adjusted = merged_weekly_macd_adjusted.sort_values('Date', ascending = True)
merged_weekly_macd_adjusted.head()

           Date     Close     Hist
359  2014-11-21  537.5000  -8.6749
358  2014-11-28  541.8300  -8.0235
357  2014-12-05  525.2600  -7.1763
356  2014-12-12  518.6600  -7.0653
355  2014-12-19  516.3500  -6.9346

In [15]:
merged_weekly_macd_adjusted.dtypes

Date     object
Close    object
Hist     object
dtype: object

In [16]:
merged_weekly_macd_adjusted['Close'] = pd.to_numeric(merged_weekly_macd_adjusted['Close'], errors='coerce')

In [17]:
merged_weekly_macd_adjusted['Hist'] = pd.to_numeric(merged_weekly_macd_adjusted['Hist'], errors='coerce')

In [18]:
merged_weekly_macd_adjusted.dtypes

Date      object
Close    float64
Hist     float64
dtype: object

In [19]:
merged_weekly_macd_adjusted['Buy'] = (merged_weekly_macd_adjusted['Hist'] > 0) & (merged_weekly_macd_adjusted['Hist'].shift(periods = 1) < 0)

In [20]:
merged_weekly_macd_adjusted['Sell'] = (merged_weekly_macd_adjusted['Hist'] < 0) & (merged_weekly_macd_adjusted['Hist'].shift(periods = 1) > 0)

In [21]:
merged_weekly_macd_adjusted.head(50)

           Date    Close     Hist    Buy   Sell
359  2014-11-21  537.500  -8.6749  False  False
358  2014-11-28  541.830  -8.0235  False  False
357  2014-12-05  525.260  -7.1763  False  False
356  2014-12-12  518.660  -7.0653  False  False
355  2014-12-19  516.350  -6.9346  False  False
354  2014-12-26  534.030  -6.9273  False  False
353  2015-01-02  524.810  -5.5290  False  False
352  2015-01-09  496.170  -4.9174  False  False
351  2015-01-16  508.080  -6.0572  False  False
350  2015-01-23  539.950  -5.3889  False  False
349  2015-01-30  534.520  -2.8782  False  False
348  2015-02-06  531.000  -1.5286  False  False
347  2015-02-13  549.010  -0.7781  False  False
346  2015-02-20  538.950   0.9991   True  False
345  2015-02-27  558.400   1.4347  False  False
344  2015-03-06  567.685   3.2535  False  False
343  2015-03-13  547.320   4.6783  False  False
342  2015-03-20  560.360   4.3514  False  False
341  2015-03-27  548.340   4.5541  False  False
340  2015-04-02  535.530   3.9006  False  False
339  2015-04-10  540.010   2.0599  False  False
338  2015-04-17  524.050   1.2001  False  False
337  2015-04-24  565.060  -0.2152  False   True
336  2015-05-01  537.900   1.3252   True  False
335  2015-05-08  538.220   0.6362  False  False
334  2015-05-15  533.850   0.1609  False  False
333  2015-05-22  540.110  -0.5516  False   True
332  2015-05-29  532.110  -0.5784  False  False
331  2015-06-05  533.330  -0.6475  False  False
330  2015-06-12  532.330  -0.8751  False  False
329  2015-06-19  536.690  -1.3051  False  False
328  2015-06-26  531.690  -0.7578  False  False
327  2015-07-02  523.400  -1.2950  False  False
326  2015-07-10  530.130  -1.9021  False  False
325  2015-07-17  672.930  -1.3113  False  False
324  2015-07-24  623.560   7.2125   True  False
323  2015-07-31  625.610   9.7409  False  False
322  2015-08-07  635.300  11.0740  False  False
321  2015-08-14  657.120  12.1883  False  False
320  2015-08-21  612.480  13.2822  False  False
319  2015-08-28  630.380   7.8225  False  False
318  2015-09-04  600.700   7.3519  False  False
317  2015-09-11  625.770   5.5753  False  False
316  2015-09-18  629.250   4.8640  False  False
315  2015-09-25  611.970   4.5589  False  False
314  2015-10-02  626.910   2.4232  False  False
313  2015-10-09  643.610   2.1644  False  False
312  2015-10-16  662.200   2.3522  False  False
311  2015-10-23  702.000   3.3791  False  False
310  2015-10-30  710.810   6.2284  False  False

In [22]:
df = merged_weekly_macd_adjusted[(merged_weekly_macd_adjusted['Sell'] == True) | (merged_weekly_macd_adjusted['Buy'] == True)] 
df = df.reset_index()
df

    index        Date    Close    Hist    Buy   Sell
0     346  2015-02-20   538.95  0.9991   True  False
1     337  2015-04-24   565.06 -0.2152  False   True
2     336  2015-05-01   537.90  1.3252   True  False
3     333  2015-05-22   540.11 -0.5516  False   True
4     324  2015-07-24   623.56  7.2125   True  False
5     299  2016-01-15   694.45 -1.4769  False   True
6     270  2016-08-05   782.22  2.1731   True  False
7     255  2016-11-18   760.54 -1.8538  False   True
8     247  2017-01-13   807.88  0.2164   True  False
9     234  2017-04-13   823.56 -0.4891  False   True
10    232  2017-04-28   905.96  0.0871   True  False
11    221  2017-07-14   955.99 -0.3792  False   True
12    219  2017-07-28   941.53  0.4021   True  False
13    218  2017-08-04   927.96 -1.4692  False   True
14    207  2017-10-20   988.20  0.6986   True  False
15    189  2018-02-23  1126.79 -1.7913  False   True
16    173  2018-06-15  1152.26  0.6376   True  False
17    159  2018-09-21  1166.09 -2.3855  False   True
18    140  2019-02-01  1110.75  0.7204   True  False
19    124  2019-05-24  1133.47 -0.7647  False   True
20    114  2019-08-02  1193.99  4.2778   True  False
21     83  2020-03-06  1298.41 -2.9022  False   True
22     73  2020-05-15  1373.19  2.3822   True  False
23     54  2020-09-25  1444.96 -3.3642  False   True
24     49  2020-10-30  1621.01  1.0237   True  False
25     37  2021-01-22  1901.05 -2.3855  False   True
26     36  2021-01-29  1835.74  5.4493   True  False
27      2  2021-09-24  2852.66 -3.8598  False   True

In [23]:
import numpy as np

In [24]:
cap = 10000
shares = 0
cap_list = []
share_list = []
df_test = df.copy()

for i, row in df_test.iterrows():
    if row['Sell']:
        #print("sell")
        cap = shares * row['Close']
        shares = 0
        #print(f"1 cap = {cap} \t shares={shares}")

        cap_list.append(cap)
        share_list.append(0)
    else:
        #print("buy")
        shares = cap / row['Close']
        cap = 0
        #print(f"2 cap = {cap} \t shares={shares}")

        cap_list.append(0)
        share_list.append(shares)

    if cap < 0:
        print("BROKE!!!")
        break

if cap >= 0:
    df_test['capital'] = cap_list
    df_test['shares'] = share_list

df_test

    index        Date    Close    Hist    Buy   Sell       capital     shares
0     346  2015-02-20   538.95  0.9991   True  False      0.000000  18.554597
1     337  2015-04-24   565.06 -0.2152  False   True  10484.460525   0.000000
2     336  2015-05-01   537.90  1.3252   True  False      0.000000  19.491468
3     333  2015-05-22   540.11 -0.5516  False   True  10527.536669   0.000000
4     324  2015-07-24   623.56  7.2125   True  False      0.000000  16.882957
5     299  2016-01-15   694.45 -1.4769  False   True  11724.369491   0.000000
6     270  2016-08-05   782.22  2.1731   True  False      0.000000  14.988583
7     255  2016-11-18   760.54 -1.8538  False   True  11399.417009   0.000000
8     247  2017-01-13   807.88  0.2164   True  False      0.000000  14.110285
9     234  2017-04-13   823.56 -0.4891  False   True  11620.666277   0.000000
10    232  2017-04-28   905.96  0.0871   True  False      0.000000  12.826909
11    221  2017-07-14   955.99 -0.3792  False   True  12262.396523   0.000000
12    219  2017-07-28   941.53  0.4021   True  False      0.000000  13.023904
13    218  2017-08-04   927.96 -1.4692  False   True  12085.662143   0.000000
14    207  2017-10-20   988.20  0.6986   True  False      0.000000  12.229976
15    189  2018-02-23  1126.79 -1.7913  False   True  13780.614497   0.000000
16    173  2018-06-15  1152.26  0.6376   True  False      0.000000  11.959640
17    159  2018-09-21  1166.09 -2.3855  False   True  13946.016315   0.000000
18    140  2019-02-01  1110.75  0.7204   True  False      0.000000  12.555495
19    124  2019-05-24  1133.47 -0.7647  False   True  14231.277166   0.000000
20    114  2019-08-02  1193.99  4.2778   True  False      0.000000  11.919092
21     83  2020-03-06  1298.41 -2.9022  False   True  15475.868797   0.000000
22     73  2020-05-15  1373.19  2.3822   True  False      0.000000  11.270013
23     54  2020-09-25  1444.96 -3.3642  False   True  16284.717612   0.000000
24     49  2020-10-30  1621.01  1.0237   True  False      0.000000  10.046032
25     37  2021-01-22  1901.05 -2.3855  False   True  19098.008289   0.000000
26     36  2021-01-29  1835.74  5.4493   True  False      0.000000  10.403439
27      2  2021-09-24  2852.66 -3.8598  False   True  29677.473022   0.000000

In [25]:
df_test

    index        Date    Close    Hist    Buy   Sell       capital     shares
0     346  2015-02-20   538.95  0.9991   True  False      0.000000  18.554597
1     337  2015-04-24   565.06 -0.2152  False   True  10484.460525   0.000000
2     336  2015-05-01   537.90  1.3252   True  False      0.000000  19.491468
3     333  2015-05-22   540.11 -0.5516  False   True  10527.536669   0.000000
4     324  2015-07-24   623.56  7.2125   True  False      0.000000  16.882957
5     299  2016-01-15   694.45 -1.4769  False   True  11724.369491   0.000000
6     270  2016-08-05   782.22  2.1731   True  False      0.000000  14.988583
7     255  2016-11-18   760.54 -1.8538  False   True  11399.417009   0.000000
8     247  2017-01-13   807.88  0.2164   True  False      0.000000  14.110285
9     234  2017-04-13   823.56 -0.4891  False   True  11620.666277   0.000000
10    232  2017-04-28   905.96  0.0871   True  False      0.000000  12.826909
11    221  2017-07-14   955.99 -0.3792  False   True  12262.396523   0.000000
12    219  2017-07-28   941.53  0.4021   True  False      0.000000  13.023904
13    218  2017-08-04   927.96 -1.4692  False   True  12085.662143   0.000000
14    207  2017-10-20   988.20  0.6986   True  False      0.000000  12.229976
15    189  2018-02-23  1126.79 -1.7913  False   True  13780.614497   0.000000
16    173  2018-06-15  1152.26  0.6376   True  False      0.000000  11.959640
17    159  2018-09-21  1166.09 -2.3855  False   True  13946.016315   0.000000
18    140  2019-02-01  1110.75  0.7204   True  False      0.000000  12.555495
19    124  2019-05-24  1133.47 -0.7647  False   True  14231.277166   0.000000
20    114  2019-08-02  1193.99  4.2778   True  False      0.000000  11.919092
21     83  2020-03-06  1298.41 -2.9022  False   True  15475.868797   0.000000
22     73  2020-05-15  1373.19  2.3822   True  False      0.000000  11.270013
23     54  2020-09-25  1444.96 -3.3642  False   True  16284.717612   0.000000
24     49  2020-10-30  1621.01  1.0237   True  False      0.000000  10.046032
25     37  2021-01-22  1901.05 -2.3855  False   True  19098.008289   0.000000
26     36  2021-01-29  1835.74  5.4493   True  False      0.000000  10.403439
27      2  2021-09-24  2852.66 -3.8598  False   True  29677.473022   0.000000